/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.link.bootime;

import com.link.Views.mainPage;
import com.view.jFrame.jDalog.errorMessage;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Janindu
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public loginPage() {
        initComponents();
        setLocationRelativeTo(null);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginDetails = new javax.swing.JPanel();
        userNameError = new javax.swing.JLabel();
        passwordError = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JPanel();
        exitButtonLl = new javax.swing.JLabel();
        linkPic = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        passwordTxtx = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginDetails.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShadowSize(10);
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        loginDetails.setBorder(dropShadowBorder1);

        userNameError.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        userNameError.setForeground(new java.awt.Color(255, 0, 51));
        userNameError.setText(" ");

        passwordError.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        passwordError.setForeground(new java.awt.Color(255, 0, 51));
        passwordError.setText(" ");

        password.setDisplayedMnemonic('P');
        password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/Key_30px.png"))); // NOI18N
        password.setLabelFor(passwordTxtx);
        password.setText("Password");

        userNameTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameTxt.setToolTipText("Enter valid User name");
        userNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });

        userName.setDisplayedMnemonic('U');
        userName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/User_32px.png"))); // NOI18N
        userName.setLabelFor(userNameTxt);
        userName.setText("User Name");
        userName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        loginButton.setBackground(new java.awt.Color(0, 0, 153));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/Lock_32px.png"))); // NOI18N
        loginButton.setMnemonic('L');
        loginButton.setText("Login");
        loginButton.setToolTipText("log your system");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setDefaultCapable(false);
        loginButton.setEnabled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/iconPeople.jpg"))); // NOI18N

        exitButton.setToolTipText("close");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });

        exitButtonLl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButtonLl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButtonLl.setText("X");
        exitButtonLl.setToolTipText("close");

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButtonLl)
                .addContainerGap())
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addComponent(exitButtonLl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        linkPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/startPageLogo.jpg"))); // NOI18N
        linkPic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 5, new java.awt.Color(0, 0, 0)));

        cancelButton.setBackground(new java.awt.Color(255, 0, 51));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/Cancel_32px.png"))); // NOI18N
        cancelButton.setMnemonic('C');
        cancelButton.setText("Cansel");
        cancelButton.setToolTipText("Exit your system");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.setDefaultCapable(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        passwordTxtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginDetailsLayout = new javax.swing.GroupLayout(loginDetails);
        loginDetails.setLayout(loginDetailsLayout);
        loginDetailsLayout.setHorizontalGroup(
            loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDetailsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(linkPic, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginDetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginDetailsLayout.createSequentialGroup()
                                .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginDetailsLayout.createSequentialGroup()
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(loginDetailsLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(passwordError, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(loginDetailsLayout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(userNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(userNameTxt)
                                            .addComponent(passwordTxtx, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                                    .addComponent(userName))
                                .addContainerGap(18, Short.MAX_VALUE))
                            .addGroup(loginDetailsLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDetailsLayout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(loginButton)
                                .addGap(40, 40, 40))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDetailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        loginDetailsLayout.setVerticalGroup(
            loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDetailsLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(userNameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordError)
                .addGap(1, 1, 1)
                .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordTxtx, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(loginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(cancelButton))
                .addContainerGap())
            .addComponent(linkPic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(loginDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
exitButton.setBackground(Color.RED);
exitButtonLl.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
exitButton.setBackground(new Color(240,240,240));        
exitButtonLl.setForeground(Color.BLACK);// TODO add your handling code here:
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
int d=JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit");
        if (d<=0) {
            System.exit(0);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_exitButtonMouseClicked

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        String s=userNameTxt.getText();
        String S="";
        if (s.equals(S)) {
                    userNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
             userNameError.setText("Enter User Name");
        }else{

            passwordTxtx.requestFocus(); 
           userNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
           userNameError.setText(" ");
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
String u=userNameTxt.getText();
String U="Janindu";
String p=passwordTxtx.getText();
String P="1234";
        if (u.equals(U)|(p.equals(P))) {
            mainPage mainPane=new mainPage();
        mainPane.setVisible(true);
        setVisible(false);
        mainPage.getUserName(u);
        }else{
            errorMessage d=new errorMessage(this, true);
            d.setVisible(true);
            userNameTxt.setText("");
            passwordTxtx.setText("");
        }
       
// TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
int j=JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit");
        if (j<=0) {
            System.exit(0);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void passwordTxtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtxActionPerformed
        String s=passwordTxtx.getText();
        String S="";
        if (s.equals(S)) {
            passwordTxtx.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
            passwordError.setText("Enter Password");
            loginButton.setEnabled(false);
        }else{
            loginButton.setEnabled(true);
            loginButton.requestFocus();
            passwordTxtx.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
            passwordError.setText(" ");
        }           // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtxActionPerformed

    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            String u=userNameTxt.getText();
String U="Janindu";
String p=passwordTxtx.getText();
String P="1234";
        if (u.equals(U)|(p.equals(P))) {
            mainPage mainPane=new mainPage();
        mainPane.setVisible(true);
        setVisible(false);
        
        }else{
            errorMessage d=new errorMessage(this, true);
            d.setVisible(true);
            userNameTxt.setText("");
            passwordTxtx.setText("");
        }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Sea_glass".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new loginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitButtonLl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel linkPic;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginDetails;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel password;
    private javax.swing.JLabel passwordError;
    private javax.swing.JPasswordField passwordTxtx;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userNameError;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
