/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.link.Views.myPanels;

import net.proteanit.sql.DbUtils;
import com.link.Model.Customer;
import com.link.controller.CustomerController;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import utilityOption.IdGenerator;

/**
 *
 * @author Janindu
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        genarateCustomerID();
        loadCustomerID();
        loadDetailToTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderSeletction = new javax.swing.ButtonGroup();
        CustomerTablet = new javax.swing.JTabbedPane();
        saveCustomerPanel = new javax.swing.JPanel();
        saveCustomerIdLbl = new javax.swing.JLabel();
        saveCustomerNameLbl = new javax.swing.JLabel();
        savaCustomerAddressLbl = new javax.swing.JLabel();
        saveCustomerSiteAddressLbl = new javax.swing.JLabel();
        saveCustomerContactLbl = new javax.swing.JLabel();
        saveCustomerGenderLbl = new javax.swing.JLabel();
        saveCustomerNameTxt = new javax.swing.JTextField();
        customerIdList = new javax.swing.JComboBox<>();
        saveCustomerAddressTxt = new javax.swing.JTextField();
        saveCustomerSiteAddressTxt = new javax.swing.JTextField();
        saveCustomerContactTxt = new javax.swing.JTextField();
        saveCustomerGederPanel = new javax.swing.JTextField();
        saveCustomerButton = new javax.swing.JLabel();
        deleteCustomerButton = new javax.swing.JLabel();
        saveCustomerNicLbl = new javax.swing.JLabel();
        saveCustomerNicTxt = new javax.swing.JTextField();
        addCustomerPanel = new javax.swing.JPanel();
        addCustomerIdLbl = new javax.swing.JLabel();
        addCustomerNameLbl = new javax.swing.JLabel();
        addCustomerNametxt = new javax.swing.JTextField();
        addCustomerAddressLbl = new javax.swing.JLabel();
        addCustomerAddressTxt = new javax.swing.JTextField();
        addCustomerSiteAddressLbl = new javax.swing.JLabel();
        addCustomerSiteAddressTxt = new javax.swing.JTextField();
        addCustomerContactLbl = new javax.swing.JLabel();
        addCustomerContactTxt = new javax.swing.JTextField();
        saveCustomerGenderLbl1 = new javax.swing.JLabel();
        addCustomerId = new javax.swing.JTextField();
        getAddress = new javax.swing.JCheckBox();
        addCustomerGederMale = new javax.swing.JRadioButton();
        addCustomerGederFemale = new javax.swing.JRadioButton();
        addCustomerButton = new javax.swing.JLabel();
        addCustomerNicTxt = new javax.swing.JTextField();
        addCustomerNicLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        printButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        setBackground(new java.awt.Color(245, 255, 255));

        saveCustomerPanel.setBackground(new java.awt.Color(0, 102, 0));

        saveCustomerIdLbl.setDisplayedMnemonic('C');
        saveCustomerIdLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerIdLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerIdLbl.setLabelFor(customerIdList);
        saveCustomerIdLbl.setText("Customer ID");

        saveCustomerNameLbl.setDisplayedMnemonic('N');
        saveCustomerNameLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerNameLbl.setLabelFor(saveCustomerNameTxt);
        saveCustomerNameLbl.setText("Name");

        savaCustomerAddressLbl.setDisplayedMnemonic('A');
        savaCustomerAddressLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        savaCustomerAddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        savaCustomerAddressLbl.setLabelFor(saveCustomerAddressTxt);
        savaCustomerAddressLbl.setText("Address");

        saveCustomerSiteAddressLbl.setDisplayedMnemonic('i');
        saveCustomerSiteAddressLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerSiteAddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerSiteAddressLbl.setLabelFor(saveCustomerSiteAddressTxt);
        saveCustomerSiteAddressLbl.setText("Site address");

        saveCustomerContactLbl.setDisplayedMnemonic('o');
        saveCustomerContactLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerContactLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerContactLbl.setLabelFor(saveCustomerContactTxt);
        saveCustomerContactLbl.setText("Contact No.");

        saveCustomerGenderLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerGenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerGenderLbl.setText("Gender");

        saveCustomerNameTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveCustomerNameTxt.setToolTipText("you can Edite Your Customer Name");
        saveCustomerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerNameTxtActionPerformed(evt);
            }
        });

        customerIdList.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        customerIdList.setToolTipText("select customer id for edite");
        customerIdList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerIdListItemStateChanged(evt);
            }
        });
        customerIdList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdListActionPerformed(evt);
            }
        });

        saveCustomerAddressTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveCustomerAddressTxt.setToolTipText("you can edite your Customer address");
        saveCustomerAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerAddressTxtActionPerformed(evt);
            }
        });

        saveCustomerSiteAddressTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveCustomerSiteAddressTxt.setToolTipText("you can edite your customer site address");
        saveCustomerSiteAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerSiteAddressTxtActionPerformed(evt);
            }
        });

        saveCustomerContactTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveCustomerContactTxt.setToolTipText("you can edite your customer contact number");
        saveCustomerContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerContactTxtActionPerformed(evt);
            }
        });

        saveCustomerGederPanel.setEditable(false);
        saveCustomerGederPanel.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveCustomerGederPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerGederPanelActionPerformed(evt);
            }
        });

        saveCustomerButton.setBackground(new java.awt.Color(204, 255, 204));
        saveCustomerButton.setDisplayedMnemonic('S');
        saveCustomerButton.setFont(new java.awt.Font("Roboto Thin", 1, 30)); // NOI18N
        saveCustomerButton.setForeground(new java.awt.Color(0, 255, 0));
        saveCustomerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));         // TODO add your handling code here:
        saveCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Save_30px.png"))); // NOI18N
        saveCustomerButton.setLabelFor(saveCustomerButton);
        saveCustomerButton.setText("Save Customer");
        saveCustomerButton.setToolTipText("save your edited details");
        saveCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        saveCustomerButton.setOpaque(true);
        saveCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveCustomerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveCustomerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveCustomerButtonMouseExited(evt);
            }
        });

        deleteCustomerButton.setBackground(new java.awt.Color(255, 204, 204));
        deleteCustomerButton.setDisplayedMnemonic('D');
        deleteCustomerButton.setFont(new java.awt.Font("Roboto Thin", 1, 30)); // NOI18N
        deleteCustomerButton.setForeground(new java.awt.Color(255, 0, 51));
        deleteCustomerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Delete_30px.png"))); // NOI18N
        deleteCustomerButton.setLabelFor(deleteCustomerButton);
        deleteCustomerButton.setText("Delete Customer");
        deleteCustomerButton.setToolTipText("customer delete your system");
        deleteCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        deleteCustomerButton.setOpaque(true);
        deleteCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteCustomerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteCustomerButtonMouseExited(evt);
            }
        });

        saveCustomerNicLbl.setDisplayedMnemonic('I');
        saveCustomerNicLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerNicLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerNicLbl.setLabelFor(addCustomerNicTxt);
        saveCustomerNicLbl.setText("NIC No.");
        saveCustomerNicLbl.setToolTipText("enter customer'd nic number");

        saveCustomerNicTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveCustomerNicTxt.setToolTipText("you can edite your customer nic number");
        saveCustomerNicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCustomerNicTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveCustomerPanelLayout = new javax.swing.GroupLayout(saveCustomerPanel);
        saveCustomerPanel.setLayout(saveCustomerPanelLayout);
        saveCustomerPanelLayout.setHorizontalGroup(
            saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                        .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(saveCustomerGenderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveCustomerContactLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveCustomerSiteAddressLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savaCustomerAddressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveCustomerIdLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveCustomerNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveCustomerAddressTxt)
                            .addComponent(saveCustomerNameTxt)
                            .addComponent(customerIdList, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveCustomerSiteAddressTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveCustomerContactTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveCustomerGederPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                        .addComponent(saveCustomerNicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveCustomerNicTxt)))
                .addContainerGap())
        );
        saveCustomerPanelLayout.setVerticalGroup(
            saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdList, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCustomerIdLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveCustomerNicLbl)
                    .addComponent(saveCustomerNicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveCustomerNameLbl)
                    .addComponent(saveCustomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(savaCustomerAddressLbl)
                    .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                        .addComponent(saveCustomerAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveCustomerSiteAddressLbl)
                    .addComponent(saveCustomerSiteAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCustomerContactLbl)
                    .addComponent(saveCustomerContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCustomerGenderLbl)
                    .addComponent(saveCustomerGederPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        CustomerTablet.addTab("Customer Manege", saveCustomerPanel);

        addCustomerPanel.setBackground(new java.awt.Color(0, 51, 0));

        addCustomerIdLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addCustomerIdLbl.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerIdLbl.setText("Customer ID");

        addCustomerNameLbl.setDisplayedMnemonic('N');
        addCustomerNameLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addCustomerNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerNameLbl.setLabelFor(addCustomerNametxt);
        addCustomerNameLbl.setText("Name");

        addCustomerNametxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerNametxt.setToolTipText("enter Customer's name for add system");
        addCustomerNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerNametxtActionPerformed(evt);
            }
        });

        addCustomerAddressLbl.setDisplayedMnemonic('d');
        addCustomerAddressLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addCustomerAddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerAddressLbl.setLabelFor(addCustomerAddressTxt);
        addCustomerAddressLbl.setText("Address");

        addCustomerAddressTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerAddressTxt.setToolTipText("enter Customer's address for add system");
        addCustomerAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerAddressTxtActionPerformed(evt);
            }
        });

        addCustomerSiteAddressLbl.setDisplayedMnemonic('t');
        addCustomerSiteAddressLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addCustomerSiteAddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerSiteAddressLbl.setLabelFor(addCustomerSiteAddressTxt);
        addCustomerSiteAddressLbl.setText("Site address");

        addCustomerSiteAddressTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerSiteAddressTxt.setToolTipText("enter Customer's site address for add system");
        addCustomerSiteAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerSiteAddressTxtActionPerformed(evt);
            }
        });

        addCustomerContactLbl.setDisplayedMnemonic('o');
        addCustomerContactLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addCustomerContactLbl.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerContactLbl.setLabelFor(addCustomerContactTxt);
        addCustomerContactLbl.setText("Contact No.");

        addCustomerContactTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerContactTxt.setToolTipText("enter Customer's contact number for add system");
        addCustomerContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerContactTxtActionPerformed(evt);
            }
        });

        saveCustomerGenderLbl1.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerGenderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerGenderLbl1.setText("Gender");

        addCustomerId.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerId.setToolTipText("you can Edite Your Customer Name");
        addCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerIdActionPerformed(evt);
            }
        });

        getAddress.setFont(new java.awt.Font("Roboto Thin", 2, 18)); // NOI18N
        getAddress.setForeground(new java.awt.Color(255, 255, 255));
        getAddress.setMnemonic('r');
        getAddress.setText("Same Address");
        getAddress.setToolTipText("same address site address and customer address");
        getAddress.setOpaque(false);

        genderSeletction.add(addCustomerGederMale);
        addCustomerGederMale.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        addCustomerGederMale.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerGederMale.setMnemonic('M');
        addCustomerGederMale.setText("Male");
        addCustomerGederMale.setToolTipText("male");
        addCustomerGederMale.setOpaque(false);
        addCustomerGederMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerGederMaleActionPerformed(evt);
            }
        });

        genderSeletction.add(addCustomerGederFemale);
        addCustomerGederFemale.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        addCustomerGederFemale.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerGederFemale.setMnemonic('F');
        addCustomerGederFemale.setText("Female");
        addCustomerGederFemale.setToolTipText("female");
        addCustomerGederFemale.setOpaque(false);
        addCustomerGederFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerGederFemaleActionPerformed(evt);
            }
        });

        addCustomerButton.setBackground(new java.awt.Color(204, 255, 204));
        addCustomerButton.setDisplayedMnemonic('A');
        addCustomerButton.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(0, 153, 0));
        addCustomerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Add User Male_30px.png"))); // NOI18N
        addCustomerButton.setLabelFor(addCustomerButton);
        addCustomerButton.setText("Add Customer");
        addCustomerButton.setToolTipText("customer add your system");
        addCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        addCustomerButton.setOpaque(true);
        addCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCustomerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCustomerButtonMouseExited(evt);
            }
        });

        addCustomerNicTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerNicTxt.setToolTipText("enter Customer's name for add system");
        addCustomerNicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerNicTxtActionPerformed(evt);
            }
        });

        addCustomerNicLbl.setDisplayedMnemonic('I');
        addCustomerNicLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addCustomerNicLbl.setForeground(new java.awt.Color(255, 255, 255));
        addCustomerNicLbl.setLabelFor(addCustomerNicTxt);
        addCustomerNicLbl.setText("NIC No.");
        addCustomerNicLbl.setToolTipText("enter customer'd nic number");

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(saveCustomerGenderLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerContactLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerSiteAddressLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerAddressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerIdLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCustomerNicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerNicTxt)
                    .addComponent(addCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCustomerAddressTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(addCustomerNametxt)
                    .addComponent(addCustomerSiteAddressTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCustomerContactTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCustomerId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                                .addComponent(addCustomerGederMale)
                                .addGap(37, 37, 37)
                                .addComponent(addCustomerGederFemale)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerIdLbl)
                    .addComponent(addCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerNicLbl)
                    .addComponent(addCustomerNicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerNameLbl)
                    .addComponent(addCustomerNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerAddressLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getAddress)
                .addGap(5, 5, 5)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerSiteAddressLbl)
                    .addComponent(addCustomerSiteAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerContactLbl)
                    .addComponent(addCustomerContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCustomerGenderLbl1)
                    .addComponent(addCustomerGederMale)
                    .addComponent(addCustomerGederFemale))
                .addGap(41, 41, 41)
                .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        CustomerTablet.addTab("Add Customer", addCustomerPanel);

        printButton.setText("Print button");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printButton)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(printButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/User_80px.png"))); // NOI18N
        jLabel1.setText("Customer Menage");

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jXTable1.setBorder(dropShadowBorder1);
        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.setToolTipText("Customer list");
        jXTable1.setDoubleBuffered(true);
        jXTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jXTable1.setGridColor(new java.awt.Color(0, 204, 102));
        jXTable1.setHorizontalScrollEnabled(true);
        jXTable1.setSelectionBackground(new java.awt.Color(255, 255, 102));
        jXTable1.setSelectionForeground(new java.awt.Color(51, 51, 255));
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jXTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(CustomerTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerTablet)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveCustomerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerNameTxtActionPerformed
saveCustomerAddressTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerNameTxtActionPerformed

    private void saveCustomerAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerAddressTxtActionPerformed
saveCustomerSiteAddressTxt.requestFocus();
    }//GEN-LAST:event_saveCustomerAddressTxtActionPerformed

    private void saveCustomerSiteAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerSiteAddressTxtActionPerformed
saveCustomerContactTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerSiteAddressTxtActionPerformed

    private void saveCustomerContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerContactTxtActionPerformed
saveCustomerButton.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerContactTxtActionPerformed

    private void saveCustomerGederPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerGederPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerGederPanelActionPerformed

    private void deleteCustomerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerButtonMouseEntered
deleteCustomerButton.setBackground(Color.red);
deleteCustomerButton.setForeground(Color.WHITE);
org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
dropShadowBorder2.setShowLeftShadow(true);
dropShadowBorder2.setShowTopShadow(true);
deleteCustomerButton.setBorder(dropShadowBorder2);        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerButtonMouseEntered

    private void deleteCustomerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerButtonMouseExited
deleteCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
deleteCustomerButton.setBackground(new java.awt.Color(255, 204, 204));
deleteCustomerButton.setForeground(new java.awt.Color(255, 0, 51));deleteCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerButtonMouseExited

    private void saveCustomerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveCustomerButtonMouseEntered
saveCustomerButton.setBackground( Color.GREEN);
saveCustomerButton.setForeground(Color.WHITE);
org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
dropShadowBorder2.setShowLeftShadow(true);
dropShadowBorder2.setShowTopShadow(true);
saveCustomerButton.setBorder(dropShadowBorder2);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerButtonMouseEntered

    private void saveCustomerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveCustomerButtonMouseExited
saveCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
saveCustomerButton.setBackground(new java.awt.Color(204, 255, 204));
saveCustomerButton.setForeground(new java.awt.Color(0, 255, 0));saveCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));         // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerButtonMouseExited

    private void addCustomerNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerNametxtActionPerformed
   String namePatten="^[a-zA-Z\\s]*$";
        Pattern pattenName=Pattern.compile(namePatten);
        Matcher regPattenName=pattenName.matcher(addCustomerNametxt.getText());
        if (!regPattenName.matches()) {
         JOptionPane.showMessageDialog(this, "Enter Valide Name");
        }else{
        addCustomerAddressTxt.requestFocus();   
        }// TODO add your handling code here:
    }//GEN-LAST:event_addCustomerNametxtActionPerformed

    private void addCustomerAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerAddressTxtActionPerformed
getAddress.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerAddressTxtActionPerformed

    private void addCustomerSiteAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerSiteAddressTxtActionPerformed
addCustomerContactTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerSiteAddressTxtActionPerformed

    private void addCustomerContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerContactTxtActionPerformed
String ContactNumberPatten="[0-9]{3}[0-9]{7}";
Pattern contactNumberPatten = Pattern.compile(ContactNumberPatten);
Matcher regcontactNnumber=contactNumberPatten.matcher(addCustomerContactTxt.getText());
        if (!regcontactNnumber.matches()) {
            JOptionPane.showMessageDialog(this, "Enter valid contact number");
        }else{
        addCustomerGederMale.requestFocus();    
        }// TODO add your handling code here:
    }//GEN-LAST:event_addCustomerContactTxtActionPerformed

    private void addCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerIdActionPerformed

    private void saveCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveCustomerButtonMouseClicked
saveButtonActionEvent();
loadDetailToTable();
    }//GEN-LAST:event_saveCustomerButtonMouseClicked

    private void addCustomerGederFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerGederFemaleActionPerformed
addCustomerButton.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerGederFemaleActionPerformed

    private void addCustomerGederMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerGederMaleActionPerformed
addCustomerButton.requestFocus();           // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerGederMaleActionPerformed

    private void addCustomerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerButtonMouseExited
addCustomerButton.setBackground(new java.awt.Color(204, 255, 204));
addCustomerButton.setForeground(new java.awt.Color(0, 153, 0));
addCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButtonMouseExited

    private void addCustomerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerButtonMouseEntered
addCustomerButton.setBackground( Color.GREEN);
addCustomerButton.setForeground(Color.WHITE);
org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
dropShadowBorder2.setShowLeftShadow(true);
dropShadowBorder2.setShowTopShadow(true);
addCustomerButton.setBorder(dropShadowBorder2);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButtonMouseEntered

    private void addCustomerNicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerNicTxtActionPerformed
 String nicPatten="^[0-9]{1,9}[VvXx]$";  
        Pattern pattenNic=Pattern.compile(nicPatten); 
        Matcher regMatcherNic=pattenNic.matcher( addCustomerNicTxt.getText());
        if (!regMatcherNic.matches()) {
            JOptionPane.showMessageDialog(this, "Not mach");
        }else{
           addCustomerNametxt.requestFocus();    
        }
             // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerNicTxtActionPerformed

    private void saveCustomerNicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCustomerNicTxtActionPerformed
saveCustomerNameTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveCustomerNicTxtActionPerformed

    private void addCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerButtonMouseClicked
        //Nic validation Pattren
        String nicPatten="^[0-9]{1,9}[VvXx]$";  
        Pattern pattenNic=Pattern.compile(nicPatten); 
        Matcher regMatcherNic=pattenNic.matcher( addCustomerNicTxt.getText());
        if (!regMatcherNic.matches()) {
            JOptionPane.showMessageDialog(this, "Not mach");
        }else{
        
            //JOptionPane.showMessageDialog(this, " mach ok ");
            String namePatten="^[a-zA-Z\\s]*$";
            Pattern pattenName=Pattern.compile(namePatten);
            Matcher regPattenName=pattenName.matcher(addCustomerNametxt.getText());
            if (!regPattenName.matches()) {
             JOptionPane.showMessageDialog(this, "Enter Valide Name");
                }else{
                    String ContactNumberPatten="[0-9]{3}[0-9]{7}";
                    Pattern contactNumberPatten = Pattern.compile(ContactNumberPatten);
                    Matcher regcontactNnumber=contactNumberPatten.matcher(addCustomerContactTxt.getText());
                        if (!regcontactNnumber.matches()) {
                         JOptionPane.showMessageDialog(this, "Enter valid contact number");
                    }else{
                           
                            AddCustomerButtonEvent();
                            
                }
            }
        }
        
        
       
        
        
    }//GEN-LAST:event_addCustomerButtonMouseClicked

    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
int i=jXTable1.getSelectedRow();
        TableModel mode=jXTable1.getModel();
        saveCustomerNameTxt.setText((String) mode.getValueAt(i, 2));
        saveCustomerNicTxt.setText((String) mode.getValueAt(i, 1));
        customerIdList.setSelectedItem(mode.getValueAt(i, 0));
    }//GEN-LAST:event_jXTable1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int d=jXTable1.getSelectedRow();
        TableModel s=jXTable1.getModel();
        saveCustomerNicTxt.setText(s.getValueAt(d, 0).toString());
        saveCustomerNameTxt.setText(s.getValueAt(d, 1).toString());
        saveCustomerAddressTxt.setText(s.getValueAt(d, 2).toString());
        saveCustomerSiteAddressTxt.setText(s.getValueAt(d, 3).toString());
        saveCustomerContactTxt.setText(s.getValueAt(d,5).toString());
        String gender=(s.getValueAt(d,4).toString());
        if (gender.equals("male")) {
            saveCustomerGederPanel.setText("Male");
        } else if(gender.equals("Female")) {
            saveCustomerGederPanel.setText("Female");
        }
               
                // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
           MessageFormat header=new MessageFormat("Customer report");
           MessageFormat footer=new MessageFormat("Page{0,number,Integer}");
        try {
            jXTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_printButtonActionPerformed

    private void customerIdListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerIdListItemStateChanged
        
  
    }//GEN-LAST:event_customerIdListItemStateChanged

    private void customerIdListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdListActionPerformed
String cust_id=(String) customerIdList.getSelectedItem();
        
        try {
            Customer c1=CustomerController.getAllDetailsCustomer(cust_id);
           saveCustomerNameTxt.setText(c1.getName());
           saveCustomerNicTxt.setText(c1.getNic());
           saveCustomerAddressTxt.setText(c1.getAddress());
           saveCustomerSiteAddressTxt.setText(c1.getSiteAddress());
           saveCustomerContactTxt.setText(c1.getContactNumber());
           saveCustomerGederPanel.setText(c1.getGender());

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_customerIdListActionPerformed

    private void deleteCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerButtonMouseClicked
deletCustomerEvent();        // TODO add your handling code here:
loadDetailToTable();
    }//GEN-LAST:event_deleteCustomerButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CustomerTablet;
    private javax.swing.JLabel addCustomerAddressLbl;
    private javax.swing.JTextField addCustomerAddressTxt;
    private javax.swing.JLabel addCustomerButton;
    private javax.swing.JLabel addCustomerContactLbl;
    private javax.swing.JTextField addCustomerContactTxt;
    private javax.swing.JRadioButton addCustomerGederFemale;
    private javax.swing.JRadioButton addCustomerGederMale;
    private javax.swing.JTextField addCustomerId;
    private javax.swing.JLabel addCustomerIdLbl;
    private javax.swing.JLabel addCustomerNameLbl;
    private javax.swing.JTextField addCustomerNametxt;
    private javax.swing.JLabel addCustomerNicLbl;
    private javax.swing.JTextField addCustomerNicTxt;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JLabel addCustomerSiteAddressLbl;
    private javax.swing.JTextField addCustomerSiteAddressTxt;
    private javax.swing.JComboBox<String> customerIdList;
    private javax.swing.JLabel deleteCustomerButton;
    private javax.swing.ButtonGroup genderSeletction;
    private javax.swing.JCheckBox getAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel savaCustomerAddressLbl;
    private javax.swing.JTextField saveCustomerAddressTxt;
    private javax.swing.JLabel saveCustomerButton;
    private javax.swing.JLabel saveCustomerContactLbl;
    private javax.swing.JTextField saveCustomerContactTxt;
    private javax.swing.JTextField saveCustomerGederPanel;
    private javax.swing.JLabel saveCustomerGenderLbl;
    private javax.swing.JLabel saveCustomerGenderLbl1;
    private javax.swing.JLabel saveCustomerIdLbl;
    private javax.swing.JLabel saveCustomerNameLbl;
    private javax.swing.JTextField saveCustomerNameTxt;
    private javax.swing.JLabel saveCustomerNicLbl;
    private javax.swing.JTextField saveCustomerNicTxt;
    private javax.swing.JPanel saveCustomerPanel;
    private javax.swing.JLabel saveCustomerSiteAddressLbl;
    private javax.swing.JTextField saveCustomerSiteAddressTxt;
    // End of variables declaration//GEN-END:variables

    private void AddCustomerButtonEvent() {
  Date d1=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(d1);
String gender=null;
boolean male=addCustomerGederMale.isSelected();
boolean female=addCustomerGederFemale.isSelected();
        if (male) {
            gender="Male";
            System.out.println(gender);
        } else if(female) {
             gender="Female";
             System.out.println(gender);
        }
    
        Customer d=new Customer(Integer.parseInt(addCustomerId.getText()),addCustomerNicTxt.getText(),addCustomerNametxt.getText(),addCustomerAddressTxt.getText(),addCustomerSiteAddressTxt.getText(),gender,addCustomerContactTxt.getText(),date);
        try {
          boolean dd=  CustomerController.addCustomer(d);
            if (dd) {
            JOptionPane.showMessageDialog(this, date);
            genarateCustomerID();
            loadDetailToTable();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void genarateCustomerID(){
        try {
            addCustomerId.setText(IdGenerator.getCustId());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void loadCustomerID() {
         ArrayList<Customer>itemlist;
        try {
            itemlist = CustomerController.getAllItem();
            for(int i=0;i<itemlist.size();i++){
          Customer item=(Customer)itemlist.get(i);
         customerIdList.addItem(Integer.toString(item.getCustId()));
      }
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
    }

    private void saveButtonActionEvent() {
            int cust_id=Integer.parseInt((String) customerIdList.getSelectedItem());
JOptionPane.showMessageDialog(saveCustomerPanel, "");        
 Date d1=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(d1);
        Customer d;
                  d=new Customer(cust_id,
                          saveCustomerNicTxt.getText(),
                          saveCustomerNameTxt.getText(),
                          saveCustomerAddressTxt.getText(),
                          saveCustomerSiteAddressTxt.getText(),
                          saveCustomerGederPanel.getText(),
                          saveCustomerContactTxt.getText(),
                          date);
        try {
            boolean c1=CustomerController.updateDetails(d);
            if (c1) {
                JOptionPane.showMessageDialog(this, "Your details is Updatrd ...!!");
                loadCustomerID();
            }else{
                    JOptionPane.showMessageDialog(this, "some one error");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void deletCustomerEvent() {
String cust_id=(String) customerIdList.getSelectedItem();
        try {
            boolean d=CustomerController.deleteCustomer(cust_id);
            if (d) {
                JOptionPane.showMessageDialog(this, saveCustomerNameTxt.getText()+"is Deleted....!!" );
                saveCustomerNameTxt.setText("");
                saveCustomerNicTxt.setText("");
                saveCustomerAddressTxt.setText("");
                saveCustomerContactTxt.setText("");
                saveCustomerGederPanel.setText("");
     int itemCount =customerIdList.getItemCount();

    for(int i=0;i<itemCount;i++){
        customerIdList.removeItemAt(0);
     }

                loadCustomerID();
                        genarateCustomerID();
            }
            else{
                JOptionPane.showMessageDialog(this, "some One is error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDetailToTable() {
        try {
            ResultSet res=CustomerController.getTable();
            jXTable1.setModel(DbUtils.resultSetToTableModel(res));
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
