/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.link.Views.myPanels;

import com.link.Model.Items;
import com.link.controller.ItemsController;
import com.view.jFrame.jDalog.selectItemCode;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import utilityOption.IdGenerator;

/**
 *
 * @author Janindu
 */
public class ItemPanel extends javax.swing.JPanel {

    private String get;
    

    /**
     * Creates new form CustomerPanel
     */
    public ItemPanel() {
        initComponents();
        itemCodeLoad();
        loadItemToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerIdList = new javax.swing.JComboBox<>();
        CustomerTablet = new javax.swing.JTabbedPane();
        saveCustomerPanel = new javax.swing.JPanel();
        saveCustomerIdLbl = new javax.swing.JLabel();
        saveItemDescripitionLbl = new javax.swing.JLabel();
        saveItemDepositePriceLbl = new javax.swing.JLabel();
        saveItemDailyRentLbl = new javax.swing.JLabel();
        saveItemQtyLbl = new javax.swing.JLabel();
        saveCustomerGenderLbl = new javax.swing.JLabel();
        saveItemDescriptionTxt = new javax.swing.JTextField();
        saveItemDepositePriceTxt = new javax.swing.JTextField();
        saveItemDailyRentTxt = new javax.swing.JTextField();
        saveItemQtyTxt = new javax.swing.JTextField();
        saveItemButton = new javax.swing.JLabel();
        deleteCustomerButton = new javax.swing.JLabel();
        saveItemNameLbl = new javax.swing.JLabel();
        saveItemCode = new javax.swing.JTextField();
        saveItemSelectCategory = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        saveItemNameTxt1 = new javax.swing.JTextField();
        addCustomerPanel = new javax.swing.JPanel();
        addItemIdLbl = new javax.swing.JLabel();
        addItemDescLbl = new javax.swing.JLabel();
        addItemDescTxt = new javax.swing.JTextField();
        addItemDepositePriceLbl = new javax.swing.JLabel();
        addItemDepositePriceTxt = new javax.swing.JTextField();
        addItemDailyRentLbl = new javax.swing.JLabel();
        addItemDailyRentTxt = new javax.swing.JTextField();
        addItemQtyOnAddLbl = new javax.swing.JLabel();
        addItemQtyOnAddTxt = new javax.swing.JTextField();
        addItemCategory = new javax.swing.JLabel();
        addItemTxt = new javax.swing.JTextField();
        addItemsButton = new javax.swing.JLabel();
        addCustomerNicTxt = new javax.swing.JTextField();
        addItemNameLbl = new javax.swing.JLabel();
        addItemSelectCategory = new javax.swing.JComboBox<>();
        addItemAddCategoryButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();

        customerIdList.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        customerIdList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Customer Id", "c001", "c002", "c003" }));
        customerIdList.setToolTipText("select customer id for edite");

        setBackground(new java.awt.Color(255, 244, 255));

        saveCustomerPanel.setBackground(new java.awt.Color(51, 0, 51));

        saveCustomerIdLbl.setDisplayedMnemonic('C');
        saveCustomerIdLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerIdLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerIdLbl.setLabelFor(customerIdList);
        saveCustomerIdLbl.setText("Item code");

        saveItemDescripitionLbl.setDisplayedMnemonic('N');
        saveItemDescripitionLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveItemDescripitionLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveItemDescripitionLbl.setLabelFor(saveItemDescriptionTxt);
        saveItemDescripitionLbl.setText("Description");

        saveItemDepositePriceLbl.setDisplayedMnemonic('A');
        saveItemDepositePriceLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveItemDepositePriceLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveItemDepositePriceLbl.setLabelFor(saveItemDepositePriceTxt);
        saveItemDepositePriceLbl.setText("Deopsite Rs.");

        saveItemDailyRentLbl.setDisplayedMnemonic('i');
        saveItemDailyRentLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveItemDailyRentLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveItemDailyRentLbl.setLabelFor(saveItemDailyRentTxt);
        saveItemDailyRentLbl.setText("Daily Rent Rs.");

        saveItemQtyLbl.setDisplayedMnemonic('o');
        saveItemQtyLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveItemQtyLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveItemQtyLbl.setLabelFor(saveItemQtyTxt);
        saveItemQtyLbl.setText("Qty on hand");

        saveCustomerGenderLbl.setDisplayedMnemonic('C');
        saveCustomerGenderLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveCustomerGenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveCustomerGenderLbl.setLabelFor(saveItemSelectCategory);
        saveCustomerGenderLbl.setText("Category");

        saveItemDescriptionTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveItemDescriptionTxt.setToolTipText("enter some deltails about ite,m");
        saveItemDescriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemDescriptionTxtActionPerformed(evt);
            }
        });

        saveItemDepositePriceTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveItemDepositePriceTxt.setToolTipText("edite deposite price");
        saveItemDepositePriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemDepositePriceTxtActionPerformed(evt);
            }
        });

        saveItemDailyRentTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveItemDailyRentTxt.setToolTipText("edite daily rent");
        saveItemDailyRentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemDailyRentTxtActionPerformed(evt);
            }
        });

        saveItemQtyTxt.setEditable(false);
        saveItemQtyTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveItemQtyTxt.setToolTipText("qty on hand");
        saveItemQtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemQtyTxtActionPerformed(evt);
            }
        });

        saveItemButton.setBackground(new java.awt.Color(204, 255, 204));
        saveItemButton.setDisplayedMnemonic('S');
        saveItemButton.setFont(new java.awt.Font("Roboto Thin", 1, 30)); // NOI18N
        saveItemButton.setForeground(new java.awt.Color(0, 255, 0));
        saveItemButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveItemButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));         // TODO add your handling code here:
        saveItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Save_30px.png"))); // NOI18N
        saveItemButton.setLabelFor(saveItemButton);
        saveItemButton.setText("Save Items");
        saveItemButton.setToolTipText("save your edited details");
        saveItemButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        saveItemButton.setOpaque(true);
        saveItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveItemButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveItemButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveItemButtonMouseExited(evt);
            }
        });
        saveItemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveItemButtonKeyPressed(evt);
            }
        });

        deleteCustomerButton.setBackground(new java.awt.Color(255, 204, 204));
        deleteCustomerButton.setDisplayedMnemonic('D');
        deleteCustomerButton.setFont(new java.awt.Font("Roboto Thin", 1, 30)); // NOI18N
        deleteCustomerButton.setForeground(new java.awt.Color(255, 0, 51));
        deleteCustomerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Delete_30px.png"))); // NOI18N
        deleteCustomerButton.setLabelFor(deleteCustomerButton);
        deleteCustomerButton.setText("Delete Items");
        deleteCustomerButton.setToolTipText("item delete your system");
        deleteCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        deleteCustomerButton.setOpaque(true);
        deleteCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteCustomerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteCustomerButtonMouseExited(evt);
            }
        });

        saveItemNameLbl.setDisplayedMnemonic('I');
        saveItemNameLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        saveItemNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveItemNameLbl.setLabelFor(saveCustomerGenderLbl);
        saveItemNameLbl.setText("Name");
        saveItemNameLbl.setToolTipText("enter customer'd nic number");

        saveItemCode.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveItemCode.setToolTipText("enter item  name");
        saveItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemCodeActionPerformed(evt);
            }
        });

        saveItemSelectCategory.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        saveItemSelectCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Customer Id", "c001", "c002", "c003" }));
        saveItemSelectCategory.setToolTipText("change item category");

        jButton1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton1.setText("Select Item code");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveItemNameTxt1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        saveItemNameTxt1.setToolTipText("enter item  name");
        saveItemNameTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemNameTxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveCustomerPanelLayout = new javax.swing.GroupLayout(saveCustomerPanel);
        saveCustomerPanel.setLayout(saveCustomerPanelLayout);
        saveCustomerPanelLayout.setHorizontalGroup(
            saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(saveCustomerGenderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveItemQtyLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveItemDailyRentLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveItemDepositePriceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveCustomerIdLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveItemDescripitionLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(saveItemNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveItemDepositePriceTxt)
                    .addComponent(saveItemDescriptionTxt)
                    .addComponent(saveItemDailyRentTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveItemQtyTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveItemSelectCategory, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveCustomerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveCustomerPanelLayout.createSequentialGroup()
                                .addComponent(saveItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveItemNameTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        saveCustomerPanelLayout.setVerticalGroup(
            saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(saveCustomerIdLbl))
                    .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveItemNameLbl)
                    .addComponent(saveItemNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveItemDescripitionLbl)
                    .addComponent(saveItemDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveItemDepositePriceLbl)
                    .addGroup(saveCustomerPanelLayout.createSequentialGroup()
                        .addComponent(saveItemDepositePriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveItemDailyRentLbl)
                    .addComponent(saveItemDailyRentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveItemQtyLbl)
                    .addComponent(saveItemQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saveCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveCustomerGenderLbl)
                    .addComponent(saveItemSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(saveItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        CustomerTablet.addTab("Items Manege", saveCustomerPanel);

        addCustomerPanel.setBackground(new java.awt.Color(102, 0, 102));

        addItemIdLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemIdLbl.setForeground(new java.awt.Color(255, 255, 255));
        addItemIdLbl.setText("Item code");

        addItemDescLbl.setDisplayedMnemonic('N');
        addItemDescLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemDescLbl.setForeground(new java.awt.Color(255, 255, 255));
        addItemDescLbl.setLabelFor(addItemDescTxt);
        addItemDescLbl.setText("Description");

        addItemDescTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addItemDescTxt.setToolTipText("enter some details");
        addItemDescTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemDescTxtActionPerformed(evt);
            }
        });

        addItemDepositePriceLbl.setDisplayedMnemonic('d');
        addItemDepositePriceLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemDepositePriceLbl.setForeground(new java.awt.Color(255, 255, 255));
        addItemDepositePriceLbl.setLabelFor(addItemDepositePriceTxt);
        addItemDepositePriceLbl.setText("Deposite Rs.");

        addItemDepositePriceTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addItemDepositePriceTxt.setToolTipText("enter deposit price ");
        addItemDepositePriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemDepositePriceTxtActionPerformed(evt);
            }
        });

        addItemDailyRentLbl.setDisplayedMnemonic('t');
        addItemDailyRentLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemDailyRentLbl.setForeground(new java.awt.Color(255, 255, 255));
        addItemDailyRentLbl.setLabelFor(addItemDailyRentTxt);
        addItemDailyRentLbl.setText("Daily Rent Rs.");

        addItemDailyRentTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addItemDailyRentTxt.setToolTipText("enter daily rent price");
        addItemDailyRentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemDailyRentTxtActionPerformed(evt);
            }
        });

        addItemQtyOnAddLbl.setDisplayedMnemonic('o');
        addItemQtyOnAddLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemQtyOnAddLbl.setForeground(new java.awt.Color(255, 255, 255));
        addItemQtyOnAddLbl.setLabelFor(addItemQtyOnAddTxt);
        addItemQtyOnAddLbl.setText("Qty on add");

        addItemQtyOnAddTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addItemQtyOnAddTxt.setToolTipText("enter how much items add your system");
        addItemQtyOnAddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemQtyOnAddTxtActionPerformed(evt);
            }
        });

        addItemCategory.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemCategory.setForeground(new java.awt.Color(255, 255, 255));
        addItemCategory.setText("Category");

        addItemTxt.setEditable(false);
        addItemTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addItemTxt.setToolTipText("you can Edite Your Customer Name");
        addItemTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemTxtActionPerformed(evt);
            }
        });

        addItemsButton.setBackground(new java.awt.Color(204, 255, 204));
        addItemsButton.setDisplayedMnemonic('A');
        addItemsButton.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        addItemsButton.setForeground(new java.awt.Color(0, 153, 0));
        addItemsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addItemsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Add User Male_30px.png"))); // NOI18N
        addItemsButton.setLabelFor(addItemsButton);
        addItemsButton.setText("Add Item");
        addItemsButton.setToolTipText("Item add your system");
        addItemsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        addItemsButton.setOpaque(true);
        addItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addItemsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addItemsButtonMouseExited(evt);
            }
        });

        addCustomerNicTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        addCustomerNicTxt.setToolTipText("enter item's name for add system");
        addCustomerNicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerNicTxtActionPerformed(evt);
            }
        });

        addItemNameLbl.setDisplayedMnemonic('I');
        addItemNameLbl.setFont(new java.awt.Font("Roboto Thin", 0, 30)); // NOI18N
        addItemNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        addItemNameLbl.setLabelFor(addCustomerNicTxt);
        addItemNameLbl.setText("Name");
        addItemNameLbl.setToolTipText("enter customer'd nic number");

        addItemSelectCategory.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        addItemSelectCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "tools", "maachines" }));
        addItemSelectCategory.setToolTipText("Select item category");
        addItemSelectCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemSelectCategoryMouseClicked(evt);
            }
        });
        addItemSelectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemSelectCategoryActionPerformed(evt);
            }
        });

        addItemAddCategoryButton.setText("...");
        addItemAddCategoryButton.setToolTipText("you can add new category");

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addItemDepositePriceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addItemIdLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addItemDescLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addItemNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addItemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addItemTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addCustomerNicTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addItemDescTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addItemDepositePriceTxt)))))
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addItemCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addItemQtyOnAddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addItemDailyRentLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addItemDailyRentTxt)
                            .addComponent(addItemQtyOnAddTxt)
                            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                                .addComponent(addItemSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addItemAddCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItemIdLbl)
                    .addComponent(addItemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItemNameLbl)
                    .addComponent(addCustomerNicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItemDescLbl)
                    .addComponent(addItemDescTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItemDepositePriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemDepositePriceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItemDailyRentLbl)
                    .addComponent(addItemDailyRentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItemQtyOnAddLbl)
                    .addComponent(addItemQtyOnAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addItemCategory)
                            .addComponent(addItemSelectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(addItemAddCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(addItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        CustomerTablet.addTab("Add Items", addCustomerPanel);

        jButton2.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton2.setText("Print All Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jXTable1.setBorder(dropShadowBorder1);
        jXTable1.setToolTipText("Item List");
        jXTable1.setDoubleBuffered(true);
        jXTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jXTable1.setGridColor(new java.awt.Color(255, 0, 255));
        jXTable1.setHorizontalScrollEnabled(true);
        jXTable1.setSelectionBackground(new java.awt.Color(0, 255, 0));
        jXTable1.setSelectionForeground(new java.awt.Color(51, 51, 255));
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jXTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jXTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jXTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/link/images/Shopping Cart_80px.png"))); // NOI18N
        jLabel1.setText("Items Menage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerTablet)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveItemDescriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemDescriptionTxtActionPerformed
saveItemDepositePriceTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemDescriptionTxtActionPerformed

    private void saveItemDepositePriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemDepositePriceTxtActionPerformed
saveItemDailyRentTxt.requestFocus();
    }//GEN-LAST:event_saveItemDepositePriceTxtActionPerformed

    private void saveItemDailyRentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemDailyRentTxtActionPerformed
saveItemQtyTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemDailyRentTxtActionPerformed

    private void saveItemQtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemQtyTxtActionPerformed
saveItemButton.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemQtyTxtActionPerformed

    private void deleteCustomerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerButtonMouseEntered
deleteCustomerButton.setBackground(Color.red);
deleteCustomerButton.setForeground(Color.WHITE);
org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
dropShadowBorder2.setShowLeftShadow(true);
dropShadowBorder2.setShowTopShadow(true);
deleteCustomerButton.setBorder(dropShadowBorder2);        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerButtonMouseEntered

    private void deleteCustomerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerButtonMouseExited
deleteCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
deleteCustomerButton.setBackground(new java.awt.Color(255, 204, 204));
deleteCustomerButton.setForeground(new java.awt.Color(255, 0, 51));deleteCustomerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerButtonMouseExited

    private void saveItemButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveItemButtonMouseEntered
saveItemButton.setBackground( Color.GREEN);
saveItemButton.setForeground(Color.WHITE);
org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
dropShadowBorder2.setShowLeftShadow(true);
dropShadowBorder2.setShowTopShadow(true);
saveItemButton.setBorder(dropShadowBorder2);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemButtonMouseEntered

    private void saveItemButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveItemButtonMouseExited
saveItemButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
saveItemButton.setBackground(new java.awt.Color(204, 255, 204));
saveItemButton.setForeground(new java.awt.Color(0, 255, 0));saveItemButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));         // TODO add your handling code here:
    }//GEN-LAST:event_saveItemButtonMouseExited

    private void addItemDescTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemDescTxtActionPerformed
addItemDepositePriceTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addItemDescTxtActionPerformed

    private void addItemDepositePriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemDepositePriceTxtActionPerformed
saveItemQtyTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addItemDepositePriceTxtActionPerformed

    private void addItemDailyRentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemDailyRentTxtActionPerformed
addItemQtyOnAddTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addItemDailyRentTxtActionPerformed

    private void addItemQtyOnAddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemQtyOnAddTxtActionPerformed
saveItemSelectCategory.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addItemQtyOnAddTxtActionPerformed

    private void addItemTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemTxtActionPerformed

    private void saveItemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveItemButtonMouseClicked
        saveButtonAction();
        loadItemToTable();
        itemCodeLoad();
    }//GEN-LAST:event_saveItemButtonMouseClicked

    private void addItemsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemsButtonMouseExited
addItemsButton.setBackground(new java.awt.Color(204, 255, 204));
addItemsButton.setForeground(new java.awt.Color(0, 153, 0));
addItemsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));        // TODO add your handling code here:
    }//GEN-LAST:event_addItemsButtonMouseExited

    private void addItemsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemsButtonMouseEntered
addItemsButton.setBackground( Color.GREEN);
addItemsButton.setForeground(Color.WHITE);
org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
dropShadowBorder2.setShowLeftShadow(true);
dropShadowBorder2.setShowTopShadow(true);
addItemsButton.setBorder(dropShadowBorder2);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemsButtonMouseEntered

    private void addItemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemsButtonMouseClicked
addItemsEvent();
// TODO add your handling code here:
    }//GEN-LAST:event_addItemsButtonMouseClicked

    private void addCustomerNicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerNicTxtActionPerformed
        addItemDescTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerNicTxtActionPerformed

    private void addItemSelectCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemSelectCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemSelectCategoryActionPerformed

    private void addItemSelectCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemSelectCategoryMouseClicked
  get=(String) customerIdList.getSelectedItem();
    }//GEN-LAST:event_addItemSelectCategoryMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void saveItemNameTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemNameTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemNameTxt1ActionPerformed

    private void saveItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemCodeActionPerformed
        saveItemDescriptionTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemCodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
selectItemCode d=new selectItemCode(null, true);
d.setVisible(true);
saveItemCode.setText(d.getCode());
setCodeAction();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jXTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXTable1KeyPressed

    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
int i=jXTable1.getSelectedRow();
        TableModel mode=jXTable1.getModel();
        int d=(int) mode.getValueAt(i, 0);
        saveItemCode.setText(d+"");
                // TODO add your handling code here:
    }//GEN-LAST:event_jXTable1MouseClicked

    private void saveItemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveItemButtonKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            saveButtonAction();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemButtonKeyPressed

    private void deleteCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerButtonMouseClicked
deleteButtonAction();
loadItemToTable();// TODO add your handling code here:
itemCodeLoad();
    }//GEN-LAST:event_deleteCustomerButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CustomerTablet;
    private javax.swing.JTextField addCustomerNicTxt;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JButton addItemAddCategoryButton;
    private javax.swing.JLabel addItemCategory;
    private javax.swing.JLabel addItemDailyRentLbl;
    private javax.swing.JTextField addItemDailyRentTxt;
    private javax.swing.JLabel addItemDepositePriceLbl;
    private javax.swing.JTextField addItemDepositePriceTxt;
    private javax.swing.JLabel addItemDescLbl;
    private javax.swing.JTextField addItemDescTxt;
    private javax.swing.JLabel addItemIdLbl;
    private javax.swing.JLabel addItemNameLbl;
    private javax.swing.JLabel addItemQtyOnAddLbl;
    private javax.swing.JTextField addItemQtyOnAddTxt;
    private javax.swing.JComboBox<String> addItemSelectCategory;
    private javax.swing.JTextField addItemTxt;
    private javax.swing.JLabel addItemsButton;
    private javax.swing.JComboBox<String> customerIdList;
    private javax.swing.JLabel deleteCustomerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JLabel saveCustomerGenderLbl;
    private javax.swing.JLabel saveCustomerIdLbl;
    private javax.swing.JPanel saveCustomerPanel;
    private javax.swing.JLabel saveItemButton;
    private javax.swing.JTextField saveItemCode;
    private javax.swing.JLabel saveItemDailyRentLbl;
    private javax.swing.JTextField saveItemDailyRentTxt;
    private javax.swing.JLabel saveItemDepositePriceLbl;
    private javax.swing.JTextField saveItemDepositePriceTxt;
    private javax.swing.JLabel saveItemDescripitionLbl;
    private javax.swing.JTextField saveItemDescriptionTxt;
    private javax.swing.JLabel saveItemNameLbl;
    private javax.swing.JTextField saveItemNameTxt1;
    private javax.swing.JLabel saveItemQtyLbl;
    private javax.swing.JTextField saveItemQtyTxt;
    private javax.swing.JComboBox<String> saveItemSelectCategory;
    // End of variables declaration//GEN-END:variables

    private void addItemsEvent() {
        Items item = new Items(Integer.parseInt(addItemTxt.getText()), addCustomerNicTxt.getText(),Double.parseDouble(addItemDepositePriceTxt.getText()), Double.parseDouble(addItemDailyRentTxt.getText()), addItemSelectCategory.getSelectedItem().toString(), Integer.parseInt(addItemQtyOnAddTxt.getText()));
      
        try {
            boolean d=ItemsController.addItem(item);
            if (d) {
                JOptionPane.showMessageDialog(this, "Item inserted to Database ........!!");
                
            }else{
                JOptionPane.showMessageDialog(this, "Some one is error insert a valied Details");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void itemCodeLoad() {
        String s = null;
        try {
            s=IdGenerator.getItemCode();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        addItemTxt.setText(s);
    }

    private void loadItemToTable(){
        jXTable1.setRowFilter(null);
        try {
            ResultSet res=ItemsController.getAllItemToTable();
            jXTable1.setModel(DbUtils.resultSetToTableModel(res));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    
    public String setItemCode(String d){
        String ds=d;
                this.get=ds;
         saveItemNameTxt1.setText(ds);
         
        System.out.println(saveItemCode.getText());
      
        return d;
    }

    private void setCodeAction() {
    saveItemCode.getText();
        try {
            Items s=ItemsController.getAllDetailsItems(saveItemCode.getText());
            saveItemNameTxt1.setText(s.getItemName());
            saveItemDepositePriceTxt.setText((s.getDepositePrice()+""));
            saveItemDailyRentTxt.setText((s.getDailyRent()+""));
            saveItemQtyTxt.setText(s.getQtyOnHand()+"");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveButtonAction() {
Items I1=new Items(
        Integer.parseInt(saveItemCode.getText()),
        saveItemNameTxt1.getText(),
        Double.parseDouble(saveItemDepositePriceTxt.getText()),
        Double.parseDouble(saveItemDailyRentTxt.getText()), 
        (String) saveItemSelectCategory.getSelectedItem(),
         Integer.parseInt(saveItemQtyTxt.getText()));
        try {
            boolean saaaa=ItemsController.updateDetails(I1);
            if (saaaa==true) {
                JOptionPane.showMessageDialog(saveItemCode, "Your item is updated.....!");
            }else{
            JOptionPane.showMessageDialog(saveItemCode, "same error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }

    private void deleteButtonAction() {
        try {
            boolean delete=ItemsController.deleteItems(saveItemCode.getText());
            if (delete) {
                JOptionPane.showMessageDialog(saveItemCode, "Item is deleted......!!");
            }else{
            //    JOptionPane.show
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
