/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.link.Views.myPanels;


import com.link.Model.Customer;
import com.link.Model.Items;
import com.link.controller.CustomerController;
import com.link.controller.ItemsController;
import com.view.jFrame.jDalog.quicAddCustomer;
import com.view.jFrame.jDalog.selectItemCode;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Janindu
 */
public class PlaceOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrderPanel() {
        initComponents();
        loadCustomerId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox6 = new javax.swing.JComboBox<>();
        mainPanel = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        Search4 = new javax.swing.JLabel();
        customerList = new javax.swing.JComboBox<>();
        Search5 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        customerSiteAddress = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        customerAddress = new javax.swing.JTextField();
        siteAddress = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        contactNumber = new javax.swing.JLabel();
        custoemerContactTxt = new javax.swing.JTextField();
        addCustomerquick = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        customerNic = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        Search6 = new javax.swing.JLabel();
        Search7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        itemCodeTxt = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        SCRCustomerAddAddressPanel9 = new javax.swing.JPanel();
        SCRCustomerAddAddressLbl11 = new javax.swing.JLabel();
        itemDailyRentTxt = new javax.swing.JTextField();
        SCRCustomerAddSiteAddressPanel5 = new javax.swing.JPanel();
        SCRCustomerAddSiteAddressLbl6 = new javax.swing.JLabel();
        saveDepositeTxt = new javax.swing.JTextField();
        SCRCustomerAddAddressPanel11 = new javax.swing.JPanel();
        SCRCustomerAddAddressLbl13 = new javax.swing.JLabel();
        SCRCustomerAddAddressTxt10 = new javax.swing.JTextField();
        SCRCustomerAddAddressPanel12 = new javax.swing.JPanel();
        SCRCustomerAddAddressLbl14 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        SCRCustomerAddAddressPanel13 = new javax.swing.JPanel();
        SCRCustomerAddAddressLbl15 = new javax.swing.JLabel();
        itemQtyTxt = new javax.swing.JTextField();
        SCRCustomerAddAddressPanel14 = new javax.swing.JPanel();
        SCRCustomerAddAddressLbl16 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel52 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        SCRCustomerAddNameLbl4 = new javax.swing.JLabel();
        itemNameTxt = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();

        jComboBox6.setEditable(true);
        jComboBox6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item Code", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "" }));
        jComboBox6.setRequestFocusEnabled(true);
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jComboBox6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox6KeyReleased(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(219, 255, 219));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 204, 204));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));

        jPanel21.setOpaque(false);

        Search4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Search4.setText("Search Customer :");

        customerList.setEditable(true);
        customerList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIC Number", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "" }));
        customerList.setRequestFocusEnabled(true);
        customerList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerListItemStateChanged(evt);
            }
        });
        customerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerListActionPerformed(evt);
            }
        });
        customerList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerListKeyReleased(evt);
            }
        });

        Search5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Search5.setText("Search Customer :");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(Search4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Search5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search4)
                    .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setText("Name");

        customerSiteAddress.setEditable(false);
        customerSiteAddress.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        customerSiteAddress.setForeground(new java.awt.Color(51, 0, 204));

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address.setText("Address");

        customerAddress.setEditable(false);
        customerAddress.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        customerAddress.setForeground(new java.awt.Color(51, 0, 204));

        siteAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        siteAddress.setText("Site Address");

        customerName.setEditable(false);
        customerName.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        customerName.setForeground(new java.awt.Color(51, 0, 204));

        contactNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactNumber.setText("Contact number");

        custoemerContactTxt.setEditable(false);
        custoemerContactTxt.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        custoemerContactTxt.setForeground(new java.awt.Color(51, 0, 204));
        custoemerContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoemerContactTxtActionPerformed(evt);
            }
        });

        addCustomerquick.setText("New Customer");
        addCustomerquick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerquickActionPerformed(evt);
            }
        });

        name1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name1.setText("Nic No.");

        customerNic.setEditable(false);
        customerNic.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        customerNic.setForeground(new java.awt.Color(51, 0, 204));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address)
                            .addComponent(name))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerName)
                            .addComponent(customerAddress)
                            .addComponent(customerNic, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNumber)
                            .addComponent(siteAddress))
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(customerSiteAddress))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(custoemerContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(name1))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCustomerquick)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerquick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(customerNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(name))
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address)
                    .addComponent(customerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteAddress)
                    .addComponent(customerSiteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumber)
                    .addComponent(custoemerContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 210));

        jPanel23.setBackground(new java.awt.Color(255, 255, 204));
        jPanel23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setOpaque(false);

        Search6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Search6.setText("Search Items :");

        Search7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Search7.setText("Search Customer :");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        itemCodeTxt.setEditable(false);
        itemCodeTxt.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        itemCodeTxt.setForeground(new java.awt.Color(204, 204, 204));
        itemCodeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCodeTxtMouseClicked(evt);
            }
        });
        itemCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(Search6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Search6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itemCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 470, 40));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        SCRCustomerAddAddressPanel9.setOpaque(false);

        SCRCustomerAddAddressLbl11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddAddressLbl11.setText("Daliy Rent price");

        itemDailyRentTxt.setEditable(false);
        itemDailyRentTxt.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        itemDailyRentTxt.setForeground(new java.awt.Color(204, 204, 204));
        itemDailyRentTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemDailyRentTxtMouseClicked(evt);
            }
        });
        itemDailyRentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDailyRentTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SCRCustomerAddAddressPanel9Layout = new javax.swing.GroupLayout(SCRCustomerAddAddressPanel9);
        SCRCustomerAddAddressPanel9.setLayout(SCRCustomerAddAddressPanel9Layout);
        SCRCustomerAddAddressPanel9Layout.setHorizontalGroup(
            SCRCustomerAddAddressPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel9Layout.createSequentialGroup()
                .addComponent(SCRCustomerAddAddressLbl11)
                .addGap(18, 18, 18)
                .addComponent(itemDailyRentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        SCRCustomerAddAddressPanel9Layout.setVerticalGroup(
            SCRCustomerAddAddressPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SCRCustomerAddAddressLbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemDailyRentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel23.add(SCRCustomerAddAddressPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 470, -1));

        SCRCustomerAddSiteAddressPanel5.setOpaque(false);

        SCRCustomerAddSiteAddressLbl6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddSiteAddressLbl6.setText("Deposite Price");

        saveDepositeTxt.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        saveDepositeTxt.setForeground(new java.awt.Color(204, 204, 204));
        saveDepositeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveDepositeTxtMouseClicked(evt);
            }
        });
        saveDepositeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDepositeTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SCRCustomerAddSiteAddressPanel5Layout = new javax.swing.GroupLayout(SCRCustomerAddSiteAddressPanel5);
        SCRCustomerAddSiteAddressPanel5.setLayout(SCRCustomerAddSiteAddressPanel5Layout);
        SCRCustomerAddSiteAddressPanel5Layout.setHorizontalGroup(
            SCRCustomerAddSiteAddressPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddSiteAddressPanel5Layout.createSequentialGroup()
                .addComponent(SCRCustomerAddSiteAddressLbl6)
                .addGap(27, 27, 27)
                .addComponent(saveDepositeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        SCRCustomerAddSiteAddressPanel5Layout.setVerticalGroup(
            SCRCustomerAddSiteAddressPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddSiteAddressPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SCRCustomerAddSiteAddressLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveDepositeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel23.add(SCRCustomerAddSiteAddressPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 470, -1));

        SCRCustomerAddAddressPanel11.setOpaque(false);

        SCRCustomerAddAddressLbl13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddAddressLbl13.setText("Decrption");

        SCRCustomerAddAddressTxt10.setEditable(false);
        SCRCustomerAddAddressTxt10.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        SCRCustomerAddAddressTxt10.setForeground(new java.awt.Color(204, 204, 204));
        SCRCustomerAddAddressTxt10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCRCustomerAddAddressTxt10MouseClicked(evt);
            }
        });
        SCRCustomerAddAddressTxt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCRCustomerAddAddressTxt10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SCRCustomerAddAddressPanel11Layout = new javax.swing.GroupLayout(SCRCustomerAddAddressPanel11);
        SCRCustomerAddAddressPanel11.setLayout(SCRCustomerAddAddressPanel11Layout);
        SCRCustomerAddAddressPanel11Layout.setHorizontalGroup(
            SCRCustomerAddAddressPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel11Layout.createSequentialGroup()
                .addComponent(SCRCustomerAddAddressLbl13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(SCRCustomerAddAddressTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        SCRCustomerAddAddressPanel11Layout.setVerticalGroup(
            SCRCustomerAddAddressPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SCRCustomerAddAddressLbl13)
                .addComponent(SCRCustomerAddAddressTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel23.add(SCRCustomerAddAddressPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 470, -1));

        SCRCustomerAddAddressPanel12.setOpaque(false);

        SCRCustomerAddAddressLbl14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddAddressLbl14.setText("Bill Number");

        jComboBox10.setEditable(true);
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        javax.swing.GroupLayout SCRCustomerAddAddressPanel12Layout = new javax.swing.GroupLayout(SCRCustomerAddAddressPanel12);
        SCRCustomerAddAddressPanel12.setLayout(SCRCustomerAddAddressPanel12Layout);
        SCRCustomerAddAddressPanel12Layout.setHorizontalGroup(
            SCRCustomerAddAddressPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel12Layout.createSequentialGroup()
                .addComponent(SCRCustomerAddAddressLbl14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
        );
        SCRCustomerAddAddressPanel12Layout.setVerticalGroup(
            SCRCustomerAddAddressPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel12Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(SCRCustomerAddAddressPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SCRCustomerAddAddressLbl14)
                    .addComponent(jComboBox10))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel23.add(SCRCustomerAddAddressPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 250, 40));

        SCRCustomerAddAddressPanel13.setOpaque(false);

        SCRCustomerAddAddressLbl15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddAddressLbl15.setText("Qty on hand");

        itemQtyTxt.setEditable(false);
        itemQtyTxt.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        itemQtyTxt.setForeground(new java.awt.Color(204, 204, 204));
        itemQtyTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemQtyTxtMouseClicked(evt);
            }
        });
        itemQtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQtyTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SCRCustomerAddAddressPanel13Layout = new javax.swing.GroupLayout(SCRCustomerAddAddressPanel13);
        SCRCustomerAddAddressPanel13.setLayout(SCRCustomerAddAddressPanel13Layout);
        SCRCustomerAddAddressPanel13Layout.setHorizontalGroup(
            SCRCustomerAddAddressPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel13Layout.createSequentialGroup()
                .addComponent(SCRCustomerAddAddressLbl15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(itemQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        SCRCustomerAddAddressPanel13Layout.setVerticalGroup(
            SCRCustomerAddAddressPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SCRCustomerAddAddressLbl15)
                .addComponent(itemQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel23.add(SCRCustomerAddAddressPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 470, -1));

        SCRCustomerAddAddressPanel14.setOpaque(false);

        SCRCustomerAddAddressLbl16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddAddressLbl16.setText("Qty ");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        javax.swing.GroupLayout SCRCustomerAddAddressPanel14Layout = new javax.swing.GroupLayout(SCRCustomerAddAddressPanel14);
        SCRCustomerAddAddressPanel14.setLayout(SCRCustomerAddAddressPanel14Layout);
        SCRCustomerAddAddressPanel14Layout.setHorizontalGroup(
            SCRCustomerAddAddressPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel14Layout.createSequentialGroup()
                .addComponent(SCRCustomerAddAddressLbl16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(104, 104, 104)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        SCRCustomerAddAddressPanel14Layout.setVerticalGroup(
            SCRCustomerAddAddressPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SCRCustomerAddAddressPanel14Layout.createSequentialGroup()
                .addGroup(SCRCustomerAddAddressPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SCRCustomerAddAddressLbl16)
                    .addComponent(jComboBox9))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel23.add(SCRCustomerAddAddressPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 400, -1));

        jPanel52.setBackground(new java.awt.Color(0, 204, 204));

        jLabel34.setBackground(new java.awt.Color(0, 204, 204));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("Clear");
        jLabel34.setOpaque(true);

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel52Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel52Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel23.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 90, 30));

        jLabel30.setBackground(new java.awt.Color(0, 255, 0));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("Add");
        jLabel30.setOpaque(true);
        jPanel23.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 70, 30));

        SCRCustomerAddNameLbl4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SCRCustomerAddNameLbl4.setText("Item Name");
        jPanel23.add(SCRCustomerAddNameLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, -1));

        itemNameTxt.setEditable(false);
        itemNameTxt.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        itemNameTxt.setForeground(new java.awt.Color(204, 204, 204));
        itemNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemNameTxtMouseClicked(evt);
            }
        });
        itemNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTxtActionPerformed(evt);
            }
        });
        jPanel23.add(itemNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, -1));

        mainPanel.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 480, 320));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Date & Time", "Description", "Item Name", "Qty", "Daily Rent", "Deposite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        mainPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 1030, 250));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Total Deposite");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("OCR-B 10 BT", 0, 24)); // NOI18N
        jLabel13.setText("xxxxxx.xx");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        mainPanel.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 150, 50));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Total Daliy Rent");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("OCR-B 10 BT", 0, 24)); // NOI18N
        jLabel15.setText("xxxxxx.xx");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        mainPanel.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 160, 50));

        jPanel28.setBackground(new java.awt.Color(204, 204, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Tranceport Details");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Need Tranceport");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Trancepoty Price");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jCheckBox1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 540, 100));

        jPanel33.setBackground(new java.awt.Color(249, 227, 227));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Items given");
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        okButton.setText("Ok");
        okButton.setEnabled(false);

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 310, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerListItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_customerListItemStateChanged

    private void customerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerListActionPerformed
String d=(String) customerList.getSelectedItem();
        try {
            Customer x=CustomerController.getAllDetailsCustomer(d);// TODO add your handling code here:
            customerNic.setText(x.getNic());
            customerName.setText(x.getName());
            customerAddress.setText(x.getAddress());
            customerSiteAddress.setText(x.getSiteAddress());
            custoemerContactTxt.setText(x.getContactNumber());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerListActionPerformed

    private void customerListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerListKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_customerListKeyReleased

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6KeyReleased

    private void itemDailyRentTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemDailyRentTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDailyRentTxtMouseClicked

    private void itemDailyRentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDailyRentTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDailyRentTxtActionPerformed

    private void saveDepositeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDepositeTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveDepositeTxtMouseClicked

    private void saveDepositeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDepositeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveDepositeTxtActionPerformed

    private void SCRCustomerAddAddressTxt10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCRCustomerAddAddressTxt10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SCRCustomerAddAddressTxt10MouseClicked

    private void SCRCustomerAddAddressTxt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCRCustomerAddAddressTxt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCRCustomerAddAddressTxt10ActionPerformed

    private void itemQtyTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemQtyTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQtyTxtMouseClicked

    private void itemQtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQtyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQtyTxtActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
boolean Select=jCheckBox2.isSelected();
        if (Select) {
            okButton.enable();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void addCustomerquickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerquickActionPerformed
        quicAddCustomer s=new quicAddCustomer();
       s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerquickActionPerformed

    private void custoemerContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoemerContactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custoemerContactTxtActionPerformed

    private void itemCodeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCodeTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTxtMouseClicked

    private void itemCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
selectItemCode d=new selectItemCode(null, true);        // TODO add your handling code here:
d.setVisible(true);
itemCodeTxt.setText(d.getCode());
searchItem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemNameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNameTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtMouseClicked

    private void itemNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SCRCustomerAddAddressLbl11;
    private javax.swing.JLabel SCRCustomerAddAddressLbl13;
    private javax.swing.JLabel SCRCustomerAddAddressLbl14;
    private javax.swing.JLabel SCRCustomerAddAddressLbl15;
    private javax.swing.JLabel SCRCustomerAddAddressLbl16;
    private javax.swing.JPanel SCRCustomerAddAddressPanel11;
    private javax.swing.JPanel SCRCustomerAddAddressPanel12;
    private javax.swing.JPanel SCRCustomerAddAddressPanel13;
    private javax.swing.JPanel SCRCustomerAddAddressPanel14;
    private javax.swing.JPanel SCRCustomerAddAddressPanel9;
    private javax.swing.JTextField SCRCustomerAddAddressTxt10;
    private javax.swing.JLabel SCRCustomerAddNameLbl4;
    private javax.swing.JLabel SCRCustomerAddSiteAddressLbl6;
    private javax.swing.JPanel SCRCustomerAddSiteAddressPanel5;
    private javax.swing.JLabel Search4;
    private javax.swing.JLabel Search5;
    private javax.swing.JLabel Search6;
    private javax.swing.JLabel Search7;
    private javax.swing.JButton addCustomerquick;
    private javax.swing.JLabel address;
    private javax.swing.JLabel contactNumber;
    private javax.swing.JTextField custoemerContactTxt;
    private javax.swing.JTextField customerAddress;
    private javax.swing.JComboBox<String> customerList;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField customerNic;
    private javax.swing.JTextField customerSiteAddress;
    private javax.swing.JTextField itemCodeTxt;
    private javax.swing.JTextField itemDailyRentTxt;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JTextField itemQtyTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField saveDepositeTxt;
    private javax.swing.JLabel siteAddress;
    // End of variables declaration//GEN-END:variables

    private void loadCustomerId() {
    
         ArrayList<Customer>itemlist;
        try {
            itemlist = CustomerController.getAllItem();
            for(int i=0;i<itemlist.size();i++){
          Customer item=(Customer)itemlist.get(i);
         customerList.addItem(Integer.toString(item.getCustId()));
      }
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
    }

    private void searchItem() {
        try {
            Items s=ItemsController.getAllDetailsItems(itemCodeTxt.getText());
            itemNameTxt.setText(s.getItemName());
            itemDailyRentTxt.setText(s.getDailyRent()+"");
            saveDepositeTxt.setText(s.getDepositePrice()+"");
           itemQtyTxt.setText(s.getQtyOnHand()+"");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PlaceOrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
