/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.link.Views;

import com.link.Views.myPanels.CustomerPanel;
import com.link.Views.myPanels.ItemPanel;
import com.link.Views.myPanels.OrderDetailsPanel;
import com.link.Views.myPanels.PlaceOrderPanel;
import com.link.Views.myPanels.Reports;
import com.link.Views.myPanels.ReturnItems;
import com.sun.scenario.Settings;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Janindu
 */
public class mainPage extends javax.swing.JFrame {

    public static void getUserName(String d) {
        getUserName(d);
    }

    /**
     * Creates new form mainPage
     */
    private Timer ti;
    GridBagLayout grid=new GridBagLayout();
    CustomerPanel customerPanel;
    ItemPanel itemPanel;
    OrderDetailsPanel OrderDetails;
    PlaceOrderPanel placeOrder;
    ReturnItems returnPanel;
    Reports reports;
  
    public mainPage() {
       
        initComponents();
        
        startPage();
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
     screenSize.getHeight();
     System.out.println(screenSize.getHeight());
System.out.println(screenSize.getWidth());
 int w=(int) screenSize.getWidth();
       int h=(int) screenSize.getHeight()-50;
        System.out.println(h);
        System.out.println(w);
   int W=w-100;
  int H=h-100; 
        setSize(w,h);
        
        customerPanel =new CustomerPanel();
        itemPanel=new ItemPanel();
        OrderDetails=new OrderDetailsPanel();
        placeOrder = new PlaceOrderPanel();
        returnPanel = new ReturnItems();
        reports=new Reports();
        newDynamicPanel.setLayout(grid);
        GridBagConstraints gc=new GridBagConstraints();
        gc.gridx = 0;
        gc.gridy = 0;
newDynamicPanel.add(customerPanel,gc);
        gc.gridx = 0;
        gc.gridy = 0;
         newDynamicPanel.add(itemPanel,gc); 
         customerPanel.setVisible(false);
         itemPanel.setVisible(false);
         placeOrder.setVisible(false);
          OrderDetails.setVisible(false);
//          reports.setVisible(false);
          setLocationRelativeTo(null);
             gc.gridx = 0;   
          gc.gridy = 0;
         newDynamicPanel.add(OrderDetails,gc); 
         customerPanel.setVisible(false);
         itemPanel.setVisible(false);
         OrderDetails.setVisible(false);
         placeOrder.setVisible(false);
         reports.setVisible(false);
              gc.gridx = 0;   
          gc.gridy = 0;
         newDynamicPanel.add(placeOrder,gc); 
         customerPanel.setVisible(false);
         itemPanel.setVisible(false);
         OrderDetails.setVisible(false);
      OrderDetails.setVisible(false);
      returnPanel.setVisible(false);
      reports.setVisible(false);
      newDynamicPanel.add(returnPanel,gc);
      newDynamicPanel.add(reports,gc);
        gc.gridx = 0;
        gc.gridy = 0;

         customerPanel.setVisible(false);
         itemPanel.setVisible(false);
         OrderDetails.setVisible(false);
      OrderDetails.setVisible(false);
      returnPanel.setVisible(false);
    reports.setVisible(false);
        newDynamicPanel.add(reports,gc);

          setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        order_Details_Button = new javax.swing.JLabel();
        order_Details_Button1 = new javax.swing.JLabel();
        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        sLogtype = new javax.swing.JLabel();
        sDate = new javax.swing.JLabel();
        sTime = new javax.swing.JLabel();
        sSystemLoading = new javax.swing.JProgressBar();
        topPanel = new javax.swing.JPanel();
        TimePanel = new javax.swing.JPanel();
        MonthLBL = new javax.swing.JLabel();
        DayLBL = new javax.swing.JLabel();
        YearLBL = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        mainPanelSP = new javax.swing.JScrollPane();
        newDynamicPanel = new javax.swing.JPanel();
        leftPaneSP = new javax.swing.JScrollPane();
        leftPanel = new javax.swing.JPanel();
        userNameButton = new javax.swing.JLabel();
        customerButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        placeOrderButton = new javax.swing.JButton();
        ReturnItems = new javax.swing.JButton();
        ReturnItems1 = new javax.swing.JButton();
        ReturnItems2 = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        fileM = new javax.swing.JMenu();
        maxMI = new javax.swing.JMenuItem();
        closeMI = new javax.swing.JMenuItem();
        reportM = new javax.swing.JMenu();
        dailyReportMI = new javax.swing.JMenuItem();
        allReportMI = new javax.swing.JMenuItem();
        settingsM = new javax.swing.JMenu();
        userSettingMI = new javax.swing.JMenuItem();
        allSettingsMI = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        CustomerMenu = new javax.swing.JMenuItem();
        ItemMenu = new javax.swing.JMenuItem();
        placeOrderMenu = new javax.swing.JMenuItem();
        itemsMenu = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenuItem();
        helpM = new javax.swing.JMenu();
        helpMI = new javax.swing.JMenuItem();
        aboutMI = new javax.swing.JMenuItem();

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        order_Details_Button.setBackground(new java.awt.Color(51, 51, 255));
        order_Details_Button.setDisplayedMnemonic('C');
        order_Details_Button.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        order_Details_Button.setForeground(new java.awt.Color(255, 255, 255));
        order_Details_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order_Details_Button.setText("[F4] Place new order");
        order_Details_Button.setToolTipText("you can add new customer and edite some customer details");
        order_Details_Button.setOpaque(true);

        order_Details_Button1.setBackground(new java.awt.Color(51, 51, 255));
        order_Details_Button1.setDisplayedMnemonic('C');
        order_Details_Button1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        order_Details_Button1.setForeground(new java.awt.Color(255, 255, 255));
        order_Details_Button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order_Details_Button1.setText("[F4] Place new order");
        order_Details_Button1.setToolTipText("you can add new customer and edite some customer details");
        order_Details_Button1.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Link Construction assoccated");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        sLogtype.setText("Log as Administor");
        jXStatusBar1.add(sLogtype);

        sDate.setText("Date");
        jXStatusBar1.add(sDate);

        sTime.setText("Time");
        jXStatusBar1.add(sTime);
        jXStatusBar1.add(sSystemLoading);

        topPanel.setBackground(new java.awt.Color(0, 0, 0));
        topPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TimePanel.setBackground(new java.awt.Color(0, 0, 0));

        MonthLBL.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        MonthLBL.setForeground(new java.awt.Color(255, 153, 0));
        MonthLBL.setText("Day");

        DayLBL.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        DayLBL.setForeground(new java.awt.Color(255, 153, 0));
        DayLBL.setText("88");

        YearLBL.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        YearLBL.setForeground(new java.awt.Color(255, 153, 0));
        YearLBL.setText("Year");

        Time.setFont(new java.awt.Font("DigifaceWide", 1, 36)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 153, 0));
        Time.setText("Time");

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimePanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(YearLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimePanelLayout.createSequentialGroup()
                .addComponent(MonthLBL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Time)
                .addComponent(DayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YearLBL))
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(TimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        newDynamicPanel.setLayout(null);
        mainPanelSP.setViewportView(newDynamicPanel);

        leftPanel.setBackground(new java.awt.Color(153, 153, 153));
        leftPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                leftPanelKeyPressed(evt);
            }
        });

        userNameButton.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        userNameButton.setForeground(new java.awt.Color(0, 0, 204));
        userNameButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameButton.setText("User Name");
        userNameButton.setToolTipText("");
        userNameButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        userNameButton.setOpaque(true);
        userNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userNameButtonMouseEntered(evt);
            }
        });

        customerButton.setBackground(new java.awt.Color(255, 255, 255));
        customerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerButton.setForeground(new java.awt.Color(51, 51, 255));
        customerButton.setText("[F5] Customer Manage");
        customerButton.setToolTipText("you can manage some customer details");
        customerButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        customerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerButtonMouseExited(evt);
            }
        });
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        customerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerButtonKeyPressed(evt);
            }
        });

        itemButton.setBackground(new java.awt.Color(255, 255, 255));
        itemButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itemButton.setForeground(new java.awt.Color(51, 51, 255));
        itemButton.setText("[F6] Items Manage");
        itemButton.setToolTipText("you can manage some items details");
        itemButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        itemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemButtonMouseExited(evt);
            }
        });
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });
        itemButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemButtonKeyPressed(evt);
            }
        });

        placeOrderButton.setBackground(new java.awt.Color(255, 255, 255));
        placeOrderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        placeOrderButton.setForeground(new java.awt.Color(51, 51, 255));
        placeOrderButton.setText("[F7] Place Order");
        placeOrderButton.setToolTipText("you can manage some items details");
        placeOrderButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        placeOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                placeOrderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                placeOrderButtonMouseExited(evt);
            }
        });
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });
        placeOrderButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placeOrderButtonKeyPressed(evt);
            }
        });

        ReturnItems.setBackground(new java.awt.Color(255, 255, 255));
        ReturnItems.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReturnItems.setForeground(new java.awt.Color(51, 51, 255));
        ReturnItems.setText("[F8] Item Return");
        ReturnItems.setToolTipText("you can manage some items details");
        ReturnItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ReturnItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReturnItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnItemsMouseExited(evt);
            }
        });
        ReturnItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnItemsActionPerformed(evt);
            }
        });
        ReturnItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReturnItemsKeyPressed(evt);
            }
        });

        ReturnItems1.setBackground(new java.awt.Color(255, 255, 255));
        ReturnItems1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReturnItems1.setForeground(new java.awt.Color(51, 51, 255));
        ReturnItems1.setText("[F9] Reports");
        ReturnItems1.setToolTipText("you can manage some items details");
        ReturnItems1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ReturnItems1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReturnItems1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnItems1MouseExited(evt);
            }
        });
        ReturnItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnItems1ActionPerformed(evt);
            }
        });
        ReturnItems1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReturnItems1KeyPressed(evt);
            }
        });

        ReturnItems2.setBackground(new java.awt.Color(255, 255, 255));
        ReturnItems2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReturnItems2.setForeground(new java.awt.Color(51, 51, 255));
        ReturnItems2.setText("Settings");
        ReturnItems2.setToolTipText("you can manage some items details");
        ReturnItems2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReturnItems2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnItems2MouseExited(evt);
            }
        });
        ReturnItems2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnItems2ActionPerformed(evt);
            }
        });
        ReturnItems2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReturnItems2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ReturnItems2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnItems1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(placeOrderButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(ReturnItems2)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        leftPaneSP.setViewportView(leftPanel);

        mainMenuBar.setBackground(new java.awt.Color(204, 204, 204));
        mainMenuBar.setForeground(new java.awt.Color(204, 255, 0));

        fileM.setMnemonic('F');
        fileM.setText("File");

        maxMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        maxMI.setText("Maximize");
        maxMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxMIActionPerformed(evt);
            }
        });
        fileM.add(maxMI);

        closeMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        closeMI.setText("close");
        closeMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMIMouseClicked(evt);
            }
        });
        closeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMIActionPerformed(evt);
            }
        });
        fileM.add(closeMI);

        mainMenuBar.add(fileM);

        reportM.setText("Reports");

        dailyReportMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        dailyReportMI.setText("Daily Reports");
        reportM.add(dailyReportMI);

        allReportMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        allReportMI.setText("All reports");
        reportM.add(allReportMI);

        mainMenuBar.add(reportM);

        settingsM.setMnemonic('S');
        settingsM.setText("Settings");

        userSettingMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        userSettingMI.setText("User Settings");
        settingsM.add(userSettingMI);

        allSettingsMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        allSettingsMI.setText("All Settings");
        allSettingsMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSettingsMIActionPerformed(evt);
            }
        });
        settingsM.add(allSettingsMI);

        mainMenuBar.add(settingsM);

        jMenu1.setText("Windows");

        CustomerMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        CustomerMenu.setText("Customer  Manage");
        CustomerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuActionPerformed(evt);
            }
        });
        jMenu1.add(CustomerMenu);

        ItemMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        ItemMenu.setText("Items Manage");
        ItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ItemMenu);

        placeOrderMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        placeOrderMenu.setText("Place Order");
        placeOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderMenuActionPerformed(evt);
            }
        });
        jMenu1.add(placeOrderMenu);

        itemsMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        itemsMenu.setText("Return Items");
        itemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itemsMenu);

        reportMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        reportMenu.setText("Reports");
        reportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuActionPerformed(evt);
            }
        });
        jMenu1.add(reportMenu);

        mainMenuBar.add(jMenu1);

        helpM.setMnemonic('H');
        helpM.setText("Help");

        helpMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpMI.setText("Help");
        helpMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMIActionPerformed(evt);
            }
        });
        helpM.add(helpMI);

        aboutMI.setText("About");
        helpM.add(aboutMI);

        mainMenuBar.add(helpM);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPaneSP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanelSP))
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXStatusBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPaneSP, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(mainPanelSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXStatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameButtonMouseEntered
userNameButton.setForeground(Color.WHITE);
userNameButton.setBackground(new Color(50,50,255));// TODO add your handling code here:
    }//GEN-LAST:event_userNameButtonMouseEntered

    private void maxMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxMIActionPerformed
        setExtendedState(mainPage.MAXIMIZED_BOTH);        // TODO add your handling code here:
    }//GEN-LAST:event_maxMIActionPerformed

    private void closeMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMIMouseClicked
        int d=JOptionPane.showConfirmDialog(null,"Are you sure want to Exit System");        // TODO add your handling code here:
        if (d<=0) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_closeMIMouseClicked

    private void closeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMIActionPerformed
        int d=JOptionPane.showConfirmDialog(null,"Are you sure want to Exit System");        // TODO add your handling code here:
        if (d<=0) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeMIActionPerformed

    private void allSettingsMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSettingsMIActionPerformed
systemSettings d=new systemSettings(this, true);
d.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_allSettingsMIActionPerformed

    private void helpMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMIActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_F5) {
            CustomerButtonAction();
        }else if (evt.getKeyCode()==KeyEvent.VK_F6) {
            ItemButtonAction();
        }
        
//       if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) {
//            jLabel2.setText("on");
//        }else{
//            jLabel2.setText("off");
//        } // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void leftPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leftPanelKeyPressed
//if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) {
//            jLabel2.setText("on");
//        }else{
//            jLabel2.setText("off");
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_leftPanelKeyPressed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        CustomerButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_customerButtonActionPerformed

    private void customerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerButtonKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_F5) {
            CustomerButtonAction();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_customerButtonKeyPressed

    private void customerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseEntered
customerButton.setBackground(new Color(51,51,255));
customerButton.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_customerButtonMouseEntered

    private void customerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseExited
customerButton.setBackground(Color.WHITE);
customerButton.setForeground(new Color(51,51,255));// TODO add your handling code here:
    }//GEN-LAST:event_customerButtonMouseExited

    private void itemButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemButtonMouseEntered
itemButton.setBackground(new Color(51,51,255));
itemButton.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_itemButtonMouseEntered

    private void itemButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemButtonMouseExited
        itemButton.setBackground(Color.WHITE);
        itemButton.setForeground(new Color(51,51,255));// TODO add your handling code here:
//
//        itemButton.setBackground(new Color(51,51,255));        // TODO add your handling code here:
    }//GEN-LAST:event_itemButtonMouseExited

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
ItemButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_itemButtonActionPerformed

    private void itemButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemButtonKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_F6) {
            ItemButtonAction();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_itemButtonKeyPressed

    private void placeOrderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOrderButtonMouseEntered

    private void placeOrderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOrderButtonMouseExited

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        placeOrderButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void placeOrderButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeOrderButtonKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_F7) {
            placeOrderButtonAction();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOrderButtonKeyPressed

    private void ReturnItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnItemsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItemsMouseEntered

    private void ReturnItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnItemsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItemsMouseExited

    private void ReturnItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnItemsActionPerformed
ReturnButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItemsActionPerformed

    private void ReturnItemsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReturnItemsKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_F8) {
            ReturnButtonAction();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItemsKeyPressed

    private void ReturnItems1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnItems1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems1MouseEntered

    private void ReturnItems1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnItems1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems1MouseExited

    private void ReturnItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnItems1ActionPerformed
ReportsButttonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems1ActionPerformed

    private void ReturnItems1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReturnItems1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems1KeyPressed

    private void ReturnItems2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnItems2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems2MouseEntered

    private void ReturnItems2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnItems2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems2MouseExited

    private void ReturnItems2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnItems2ActionPerformed
      systemSettings dd=new systemSettings(this, true);
      dd.setVisible(true);
    }//GEN-LAST:event_ReturnItems2ActionPerformed

    private void ReturnItems2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReturnItems2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItems2KeyPressed

    private void ItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuActionPerformed
ItemButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_ItemMenuActionPerformed

    private void CustomerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuActionPerformed
CustomerButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerMenuActionPerformed

    private void placeOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderMenuActionPerformed
placeOrderButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_placeOrderMenuActionPerformed

    private void itemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsMenuActionPerformed
ReturnButtonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_itemsMenuActionPerformed

    private void reportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuActionPerformed
ReportsButttonAction();        // TODO add your handling code here:
    }//GEN-LAST:event_reportMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CustomerMenu;
    private javax.swing.JLabel DayLBL;
    private javax.swing.JMenuItem ItemMenu;
    private javax.swing.JLabel MonthLBL;
    private javax.swing.JButton ReturnItems;
    private javax.swing.JButton ReturnItems1;
    private javax.swing.JButton ReturnItems2;
    private javax.swing.JLabel Time;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JLabel YearLBL;
    private javax.swing.JMenuItem aboutMI;
    private javax.swing.JMenuItem allReportMI;
    private javax.swing.JMenuItem allSettingsMI;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JMenuItem closeMI;
    private javax.swing.JButton customerButton;
    private javax.swing.JMenuItem dailyReportMI;
    private javax.swing.JMenu fileM;
    private javax.swing.JMenu helpM;
    private javax.swing.JMenuItem helpMI;
    private javax.swing.JButton itemButton;
    private javax.swing.JMenuItem itemsMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private javax.swing.JScrollPane leftPaneSP;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JScrollPane mainPanelSP;
    private javax.swing.JMenuItem maxMI;
    private javax.swing.JPanel newDynamicPanel;
    private javax.swing.JLabel order_Details_Button;
    private javax.swing.JLabel order_Details_Button1;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JMenuItem placeOrderMenu;
    private javax.swing.JMenu reportM;
    private javax.swing.JMenuItem reportMenu;
    private javax.swing.JLabel sDate;
    private javax.swing.JLabel sLogtype;
    private javax.swing.JProgressBar sSystemLoading;
    private javax.swing.JLabel sTime;
    private javax.swing.JMenu settingsM;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel userNameButton;
    private javax.swing.JMenuItem userSettingMI;
    // End of variables declaration//GEN-END:variables
   public  void TimeAndDate(){
       Calendar  t=new GregorianCalendar();
      int s=t.get(Calendar.SECOND);
       int m=t.get(Calendar.MINUTE);
       int h=t.get(Calendar.HOUR);
       int c=t.get(Calendar.AM_PM);
       int date=t.get(Calendar.DATE);
       int month=t.get(Calendar.MONTH);
       int year=t.get(Calendar.YEAR);
       String d=null;
       if(c==1){
           d="PM";
       }else{
          d="AM";
       }
       String mon=null;
        switch (month) {
            case 0:
                mon="January";
                break;
            case 1:
                mon="February";
                break;
            case 2:
                mon="March";
                break;
            case 3:
                mon="April";
                break;
            case 4:
                mon="May";
                break;
            case 5:
                mon="June";
                break;
            case 6:
                mon="July";
                break;
            case 7:
                mon="August";
                break;
            case 8:
                mon="September";
                break;
            case 9:
                mon="October";
                break;
            case 10:
                mon="November";
                break;
            default:
                mon="December";
                break;
        }
        
       
       Time.setText(h+" : "+m+" : "+s+" "+d);
       DayLBL.setText(date+"");
       MonthLBL.setText(mon+"");
       YearLBL.setText(year+"");
       sTime.setText(h+" : "+m+" : "+s+" "+d);
       sDate.setText(date+"/"+mon+"/"+year);
     
   }
    public void startPage() {
        
        setLocationRelativeTo(null);
           ti =new Timer(950,new ActionListener() {
           
               @Override 
            public void actionPerformed(ActionEvent e) {
             
                TimeAndDate();
       
               
            }
        });
       ti.start();  
    }

    private void CustomerButtonAction() {
        placeOrder.setVisible(false);
        itemPanel.setVisible(false);
        customerPanel.setVisible(true);
    }

    private void ItemButtonAction() {
        placeOrder.setVisible(false);
        customerPanel.setVisible(false);
        itemPanel.setVisible(true);
    }

    private void placeOrderButtonAction() {
        placeOrder.setVisible(true);
        customerPanel.setVisible(false);
        itemPanel.setVisible(false);
        reports.setVisible(false);
        returnPanel.setVisible(false);
        
    }

    private void ReturnButtonAction() {
        placeOrder.setVisible(false);
        customerPanel.setVisible(false);
        itemPanel.setVisible(false);
        reports.setVisible(false);
        returnPanel.setVisible(true);
    }

    private void ReportsButttonAction() {
        placeOrder.setVisible(false);
        customerPanel.setVisible(false);
        itemPanel.setVisible(false);
        returnPanel.setVisible(false);
        reports.setVisible(true);
    }
    

}
