/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.jFrame.jDalog;

import com.link.Model.Customer;
import com.link.Views.myPanels.CustomerPanel;
import com.link.controller.CustomerController;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import utilityOption.IdGenerator;

/**
 *
 * @author Janindu
 */
public class quicAddCustomer extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form quicAddCustomer
     */
    public quicAddCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        genarateCustomerID();
        setLocationRelativeTo(null);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        genarateCustomerID();
    }

    public quicAddCustomer() {
         //super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        custId = new javax.swing.JLabel();
        addCustomerId = new javax.swing.JTextField();
        customerNameTxt = new javax.swing.JTextField();
        custNameLbl = new javax.swing.JLabel();
        custNicLbl = new javax.swing.JLabel();
        custNicTxt = new javax.swing.JTextField();
        custAddressLbl = new javax.swing.JLabel();
        custAddressTxt = new javax.swing.JTextField();
        custAddressLbl1 = new javax.swing.JLabel();
        custSiteAddress = new javax.swing.JTextField();
        sameAddress = new javax.swing.JCheckBox();
        custConLbl = new javax.swing.JLabel();
        custConTxt = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        custConLbl1 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        custId.setBackground(new java.awt.Color(255, 255, 255));
        custId.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custId.setForeground(new java.awt.Color(255, 255, 255));
        custId.setText("Customer ID");

        addCustomerId.setEditable(false);
        addCustomerId.setBackground(new java.awt.Color(204, 204, 204));
        addCustomerId.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        addCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerIdActionPerformed(evt);
            }
        });

        customerNameTxt.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        customerNameTxt.setToolTipText("Enter Customer's Name");
        customerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTxtActionPerformed(evt);
            }
        });

        custNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        custNameLbl.setDisplayedMnemonic('N');
        custNameLbl.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        custNameLbl.setText("Name           ");
        custNameLbl.setToolTipText("");

        custNicLbl.setBackground(new java.awt.Color(255, 255, 255));
        custNicLbl.setDisplayedMnemonic('I');
        custNicLbl.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custNicLbl.setForeground(new java.awt.Color(255, 255, 255));
        custNicLbl.setText("NIC No.");
        custNicLbl.setToolTipText("");

        custNicTxt.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        custNicTxt.setToolTipText("Enter Customer's NIC number");
        custNicTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNicTxtActionPerformed(evt);
            }
        });

        custAddressLbl.setBackground(new java.awt.Color(255, 255, 255));
        custAddressLbl.setDisplayedMnemonic('d');
        custAddressLbl.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custAddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        custAddressLbl.setText("Address");
        custAddressLbl.setToolTipText("");

        custAddressTxt.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        custAddressTxt.setToolTipText("Enter Customer's Addres");
        custAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddressTxtActionPerformed(evt);
            }
        });

        custAddressLbl1.setBackground(new java.awt.Color(255, 255, 255));
        custAddressLbl1.setDisplayedMnemonic('N');
        custAddressLbl1.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custAddressLbl1.setForeground(new java.awt.Color(255, 255, 255));
        custAddressLbl1.setText("Site Address");
        custAddressLbl1.setToolTipText("");

        custSiteAddress.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        custSiteAddress.setToolTipText("Enter Customer's Site Address");
        custSiteAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custSiteAddressActionPerformed(evt);
            }
        });

        sameAddress.setFont(new java.awt.Font("Roboto Thin", 2, 14)); // NOI18N
        sameAddress.setForeground(new java.awt.Color(255, 255, 255));
        sameAddress.setMnemonic('e');
        sameAddress.setText("Same Address");
        sameAddress.setToolTipText("Get address for site Address");
        sameAddress.setOpaque(false);
        sameAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sameAddressActionPerformed(evt);
            }
        });

        custConLbl.setBackground(new java.awt.Color(255, 255, 255));
        custConLbl.setDisplayedMnemonic('N');
        custConLbl.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custConLbl.setForeground(new java.awt.Color(255, 255, 255));
        custConLbl.setText("Contact No.");
        custConLbl.setToolTipText("");

        custConTxt.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        custConTxt.setToolTipText("Enter Customer's Contact Number");
        custConTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custConTxtActionPerformed(evt);
            }
        });

        addCustomerButton.setBackground(new java.awt.Color(255, 255, 255));
        addCustomerButton.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        addCustomerButton.setForeground(new java.awt.Color(255, 0, 255));
        addCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon/Add User Male_40px.png"))); // NOI18N
        addCustomerButton.setMnemonic('r');
        addCustomerButton.setText("Add Customer");
        addCustomerButton.setToolTipText("Add @Custoer yor System");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        custConLbl1.setBackground(new java.awt.Color(255, 255, 255));
        custConLbl1.setDisplayedMnemonic('N');
        custConLbl1.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        custConLbl1.setForeground(new java.awt.Color(255, 255, 255));
        custConLbl1.setText("Gender");
        custConLbl1.setToolTipText("");

        male.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setMnemonic('M');
        male.setText("Male");
        male.setToolTipText("Male");
        male.setOpaque(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setMnemonic('F');
        female.setText("Female");
        female.setToolTipText("Female");
        female.setOpaque(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Customer Form");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custId)
                            .addComponent(custNicLbl)
                            .addComponent(custNameLbl)
                            .addComponent(custAddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custAddressLbl1)
                            .addComponent(custConLbl)
                            .addComponent(custConLbl1)
                            .addComponent(cancelButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custConTxt)
                            .addComponent(custSiteAddress)
                            .addComponent(custAddressTxt)
                            .addComponent(customerNameTxt)
                            .addComponent(custNicTxt)
                            .addComponent(addCustomerId)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sameAddress)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(female)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custNicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custNicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custAddressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(sameAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custAddressLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custSiteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(custConLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custConTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custConLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(male)
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void addCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerIdActionPerformed

    private void customerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTxtActionPerformed
        custAddressTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTxtActionPerformed

    private void custNicTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNicTxtActionPerformed
        customerNameTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_custNicTxtActionPerformed

    private void custAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddressTxtActionPerformed
        sameAddress.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_custAddressTxtActionPerformed

    private void custSiteAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custSiteAddressActionPerformed
        custConTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_custSiteAddressActionPerformed

    private void sameAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sameAddressActionPerformed
        boolean s=sameAddress.isSelected();        // TODO add your handling code here:
        if (s) {
            custSiteAddress.setText(custAddressTxt.getText());
            custConTxt.requestFocus();
        }else{
            custSiteAddress.requestFocus();
        }
    }//GEN-LAST:event_sameAddressActionPerformed

    private void custConTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custConTxtActionPerformed
        male.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_custConTxtActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
       String gender= null;
       boolean m=male.isSelected();
       boolean f=female.isSelected();
        if (m) {
            gender="Male";
            
        }else if(f){
            gender="Female";
            
        }
        Date d1=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(d1);
       
        Customer ss=new Customer(
                Integer.parseInt(addCustomerId.getText()),
                custNicTxt.getText(),
                customerNameTxt.getText(),
                custAddressTxt.getText(),
                custSiteAddress.getText(),
                gender,
                custConTxt.getText(), 
                date);
        try {
            boolean add=CustomerController.addCustomer(ss);
            if (add) {
                 jDialogAddCustomer d=new jDialogAddCustomer(null, true);
        d.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,"have  Some error");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(quicAddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(quicAddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed

        addCustomerButton.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        addCustomerButton.requestFocus();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quicAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quicAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quicAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quicAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quicAddCustomer dialog = new quicAddCustomer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField addCustomerId;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel custAddressLbl;
    private javax.swing.JLabel custAddressLbl1;
    private javax.swing.JTextField custAddressTxt;
    private javax.swing.JLabel custConLbl;
    private javax.swing.JLabel custConLbl1;
    private javax.swing.JTextField custConTxt;
    private javax.swing.JLabel custId;
    private javax.swing.JLabel custNameLbl;
    private javax.swing.JLabel custNicLbl;
    private javax.swing.JTextField custNicTxt;
    private javax.swing.JTextField custSiteAddress;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JCheckBox sameAddress;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
   
    public void genarateCustomerID(){
        try {
            String d=IdGenerator.getCustId();
            System.out.println(d+"ddd");
            addCustomerId.setText(d);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
}
